package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lefter001_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(6);
    _jspx_dependants.add("/WEB-INF/fulong-portal.tld");
    _jspx_dependants.add("/WEB-INF/fulong-site.tld");
    _jspx_dependants.add("/WEB-INF/struts-bean.tld");
    _jspx_dependants.add("/WEB-INF/struts-logic.tld");
    _jspx_dependants.add("/WEB-INF/struts-html.tld");
    _jspx_dependants.add("/WEB-INF/struts-tiles.tld");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<table cellspacing=\"0\" cellpadding=\"0\" width=\"110\" border=\"0\">\n");
      out.write("  <tbody>\n");
      out.write("    <tr>\n");
      out.write("      <td>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/i_top_s.gif\" /></td>\n");
      out.write("            <td width=\"100%\"><a href=\"/sites/gamioa/channelYhzm.jsp\">办公桌面</a></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_sche.gif\" /></td>\n");
      out.write("            <td width=\"100%\"><a href=\"/sites/gamioa/channelGzjh.jsp\">工作计划</a></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_iki.gif\" /></td>\n");
      out.write("            <td width=\"100%\"><a href=\"/sites/gamioa/hygl.jsp\">会议管理 </a></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_sisetu.gif\" /></td>\n");
      out.write("            <td width=\"100%\"><a href=\"/sites/gamioa/channelXwdt.jsp\">新闻动态</a></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_keijiban.gif\" /></td>\n");
      out.write("            <td width=\"100%\"><a href=\"/sites/gamioa/channelTzgg.jsp\">通知公告</a></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_todo.gif\" /></td>\n");
      out.write("            <td width=\"100%\"><a href=\"/sites/gamioa/channelWjcy.jsp\">文件传阅</a></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"/sites/gamioa/pic/zzjg.bmp\" /></td>\n");
      out.write("            <td width=\"100%\"><a href=\"/sites/gamioa/zzgj.jsp\">组织机构 </a></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_densi.gif\" /></td>\n");
      out.write("            <td width=\"100%\">岗位职责</td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_address.gif\" /></td>\n");
      out.write("            <td width=\"100%\">通讯簿</td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_mail.gif\" /></td>\n");
      out.write("            <td width=\"100%\">电子邮件&nbsp;</td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_todo.gif\" /></td>\n");
      out.write("            <td width=\"100%\">万方数据</td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_net.gif\" /></td>\n");
      out.write("            <td width=\"100%\">文件共享</td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_densi.gif\" /></td>\n");
      out.write("            <td width=\"100%\">规章制度</td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_todo.gif\" /></td>\n");
      out.write("            <td width=\"100%\"><a href=\"/sites/gamioa/cygl.jsp\">餐饮管理</a></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td valign=\"top\"><img height=\"23\" alt=\"\" width=\"25\" src=\"http://oa.fulong.com.cn/oasv1/img/ico_densi.gif\" /></td>\n");
      out.write("            <td width=\"100%\"><a href=\"/sites/gamioa/channelBdyj2.jsp\">病毒预警</a></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\n");
      out.write("        <tbody>\n");
      out.write("          <tr>\n");
      out.write("            <td background=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\"><img height=\"5\" alt=\"\" width=\"4\" src=\"http://oa.fulong.com.cn/oasv1/img/tensen.gif\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("      </td>\n");
      out.write("    </tr>\n");
      out.write("  </tbody>\n");
      out.write("</table>\n");
      out.write("<br />");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
