///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

package com.fulong.lyvc.message;

/**
 * AddConference
 * 
 * 龙驭视频会议系统 v3.0
 * 
 * 版权所有：北京中科辅龙计算机技术股份有限公司 2009
 * 
 * @author 李雄锋
 * 
 * 最后修改时间：2010-9-10
 */

public class AddConference extends BaseMessage{

	public static final int id = 65;

	public boolean isStarted;
	public boolean isEnded;
	public java.util.Date startTime;
	public java.util.Date endTime;
	public String creatorId;
	public String conId;
	public String conModelId;
	public String conName;
	public String conDesc;
	public String conFilesDesc;
	public String conFilesURL;

	public String toXML() {
		StringBuffer xml = new StringBuffer();
		xml.append("<lyvcmessage>");
		xml.append("<id>" + id + "</id>");
		xml.append("<_senderid>" + this.getSenderId() + "</_senderid>");
		xml.append("<_conferenceid>" + this.getConferenceId() + "</_conferenceid>");
		xml.append("<isStarted>");
		if( this.isStarted){
			xml.append(1);
		} else {
			xml.append(0);
		}
		xml.append("</isStarted>");
		xml.append("<isEnded>");
		if( this.isEnded){
			xml.append(1);
		} else {
			xml.append(0);
		}
		xml.append("</isEnded>");
		xml.append("<startTime>");
		if(this.startTime != null) {
			xml.append(this.startTime.getTime());
		} else {
			xml.append(0);
		}
		xml.append("</startTime>");
		xml.append("<endTime>");
		if(this.endTime != null) {
			xml.append(this.endTime.getTime());
		} else {
			xml.append(0);
		}
		xml.append("</endTime>");
		xml.append("<creatorId>" + this.creatorId + "</creatorId>");
		xml.append("<conId>" + this.conId + "</conId>");
		xml.append("<conModelId>" + this.conModelId + "</conModelId>");
		xml.append("<conName>");
		if(this.conName != null) {
			xml.append(encodeHtmlEscape(this.conName));
		}
		xml.append("</conName>");
		xml.append("<conDesc>");
		if(this.conDesc != null) {
			xml.append(encodeHtmlEscape(this.conDesc));
		}
		xml.append("</conDesc>");
		xml.append("<conFilesDesc>");
		if(this.conFilesDesc != null) {
			xml.append(encodeHtmlEscape(this.conFilesDesc));
		}
		xml.append("</conFilesDesc>");
		xml.append("<conFilesURL>");
		if(this.conFilesURL != null) {
			xml.append(encodeHtmlEscape(this.conFilesURL));
		}
		xml.append("</conFilesURL>");
		xml.append("</lyvcmessage>");
		
		return xml.toString();
	}

	public void fromXML(String xmlString) throws MessageFormatException {
		String tagContent;
		
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_senderid");
		this.setSenderId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_conferenceid");
		this.setConferenceId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "isStarted");
		if( tagContent.equals("0")) {
			this.isStarted = false;
		} else {
			this.isStarted = true;
		}
		
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "isEnded");
		if( tagContent.equals("0")) {
			this.isEnded = false;
		} else {
			this.isEnded = true;
		}
		
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "startTime");
		this.startTime = new java.util.Date(Long.parseLong(tagContent));
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "endTime");
		this.endTime = new java.util.Date(Long.parseLong(tagContent));
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "creatorId");
		this.creatorId = tagContent;
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "conId");
		this.conId = tagContent;
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "conModelId");
		this.conModelId = tagContent;
		this.conName = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "conName"));
		this.conDesc = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "conDesc"));
		this.conFilesDesc = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "conFilesDesc"));
		this.conFilesURL = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "conFilesURL"));
	}
}
