///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

package com.fulong.lyvc.message;

/**
 * Advertizement
 * 
 * 龙驭视频会议系统 v3.0
 * 
 * 版权所有：北京中科辅龙计算机技术股份有限公司 2009
 * 
 * @author 李雄锋
 * 
 * 最后修改时间：2010-9-10
 */

public class Advertizement extends BaseMessage{

	public static final int id = 187;

	public String homepage;
	public String mainframe;
	public String roomframe;

	public String toXML() {
		StringBuffer xml = new StringBuffer();
		xml.append("<lyvcmessage>");
		xml.append("<id>" + id + "</id>");
		xml.append("<_senderid>" + this.getSenderId() + "</_senderid>");
		xml.append("<_conferenceid>" + this.getConferenceId() + "</_conferenceid>");
		xml.append("<homepage>");
		if(this.homepage != null) {
			xml.append(encodeHtmlEscape(this.homepage));
		}
		xml.append("</homepage>");
		xml.append("<mainframe>");
		if(this.mainframe != null) {
			xml.append(encodeHtmlEscape(this.mainframe));
		}
		xml.append("</mainframe>");
		xml.append("<roomframe>");
		if(this.roomframe != null) {
			xml.append(encodeHtmlEscape(this.roomframe));
		}
		xml.append("</roomframe>");
		xml.append("</lyvcmessage>");
		
		return xml.toString();
	}

	public void fromXML(String xmlString) throws MessageFormatException {
		String tagContent;
		
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_senderid");
		this.setSenderId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_conferenceid");
		this.setConferenceId(tagContent);
		this.homepage = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "homepage"));
		this.mainframe = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "mainframe"));
		this.roomframe = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "roomframe"));
	}

}
