///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

package com.fulong.lyvc.message;

/**
 * CheckVersion
 * 
 * 龙驭视频会议系统 v3.0
 * 
 * 版权所有：北京中科辅龙计算机技术股份有限公司 2009
 * 
 * @author 李雄锋
 * 
 * 最后修改时间：2010-9-10
 */

public class CheckVersion extends BaseMessage{

	public static final int id = 182;

	public boolean bHasNewVersion;
	public boolean bNeedUpdate;
	public int version;
	public String domain;
	
	public String toXML() {
		StringBuffer xml = new StringBuffer();
		xml.append("<lyvcmessage>");
		xml.append("<id>" + id + "</id>");
		xml.append("<_senderid>" + this.getSenderId() + "</_senderid>");
		xml.append("<_conferenceid>" + this.getConferenceId() + "</_conferenceid>");
		xml.append("<domain>" + this.domain + "</domain>");
		xml.append("<bHasNewVersion>");
		if( this.bHasNewVersion){
			xml.append(1);
		} else {
			xml.append(0);
		}
		xml.append("</bHasNewVersion>");
		xml.append("<bNeedUpdate>");
		if( this.bNeedUpdate){
			xml.append(1);
		} else {
			xml.append(0);
		}
		xml.append("</bNeedUpdate>");
		xml.append("<version>" + this.version + "</version>");
		xml.append("</lyvcmessage>");
		
		return xml.toString();
	}

	public void fromXML(String xmlString) throws MessageFormatException {
		String tagContent;
		
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_senderid");
		this.setSenderId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_conferenceid");
		this.setConferenceId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "bHasNewVersion");
		if( tagContent.equals("0")) {
			this.bHasNewVersion = false;
		} else {
			this.bHasNewVersion = true;
		}
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "bNeedUpdate");
		if( tagContent.equals("0")) {
			this.bNeedUpdate = false;
		} else {
			this.bNeedUpdate = true;
		}
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "version");
		this.version = Integer.parseInt(tagContent);
		this.domain = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "domain"));;
	}

}
