///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

package com.fulong.lyvc.message;

/**
 * Leaveword
 * 
 * 龙驭视频会议系统 v3.0
 * 
 * 版权所有：北京中科辅龙计算机技术股份有限公司 2009
 * 
 * @author 李雄锋
 * 
 * 最后修改时间：2010-9-10
 */

public class Leaveword extends BaseMessage{

	public static final int id = 144;

	public java.util.Date sendDate;
	public String receiverId;
	public String content;
	public String senderName;

	public String toXML() {
		StringBuffer xml = new StringBuffer();
		xml.append("<lyvcmessage>");
		xml.append("<id>" + id + "</id>");
		xml.append("<_senderid>" + this.getSenderId() + "</_senderid>");
		xml.append("<_conferenceid>" + this.getConferenceId() + "</_conferenceid>");
		xml.append("<sendDate>");
		if(this.sendDate != null) {
			xml.append(this.sendDate.getTime());
		} else {
			xml.append(0);
		}
		xml.append("</sendDate>");
		xml.append("<receiverId>" + this.receiverId + "</receiverId>");
		xml.append("<content>");
		if(this.content != null) {
			xml.append(encodeHtmlEscape(this.content));
		}
		xml.append("</content>");
		xml.append("<senderName>");
		if(this.senderName != null) {
			xml.append(encodeHtmlEscape(this.senderName));
		}
		xml.append("</senderName>");
		xml.append("</lyvcmessage>");
		
		return xml.toString();
	}

	public void fromXML(String xmlString) throws MessageFormatException {
		String tagContent;
		
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_senderid");
		this.setSenderId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_conferenceid");
		this.setConferenceId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "sendDate");
		this.sendDate = new java.util.Date(Long.parseLong(tagContent));
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "receiverId");
		this.receiverId = tagContent;
		this.content = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "content"));
		this.senderName = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "senderName"));
	}

}
