///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

package com.fulong.lyvc.message;

/**
 * Login
 * 
 * 龙驭视频会议系统 v3.0
 * 
 * 版权所有：北京中科辅龙计算机技术股份有限公司 2009
 * 
 * @author 李雄锋
 * 
 * 最后修改时间：2010-9-10
 */

public class Login extends BaseMessage{

	public static final int id = 35;

	public int avCompressionCardChannelNumber;
	public String username;
	public String password;
	public String domain;

	public String toXML() {
		StringBuffer xml = new StringBuffer();
		xml.append("<lyvcmessage>");
		xml.append("<id>" + id + "</id>");
		xml.append("<_senderid>" + this.getSenderId() + "</_senderid>");
		xml.append("<_conferenceid>" + this.getConferenceId() + "</_conferenceid>");
		xml.append("<domain>" + this.domain + "</domain>");
		xml.append("<avCompressionCardChannelNumber>" + this.avCompressionCardChannelNumber + "</avCompressionCardChannelNumber>");
		xml.append("<username>");
		if(this.username != null) {
			xml.append(encodeHtmlEscape(this.username));
		}
		xml.append("</username>");
		xml.append("<password>");
		if(this.password != null) {
			xml.append(encodeHtmlEscape(this.password));
		}
		xml.append("</password>");
		xml.append("</lyvcmessage>");
		
		return xml.toString();
	}

	public void fromXML(String xmlString) throws MessageFormatException {
		String tagContent;
		
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_senderid");
		this.setSenderId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_conferenceid");
		this.setConferenceId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "avCompressionCardChannelNumber");
		this.avCompressionCardChannelNumber = Integer.parseInt(tagContent);
		this.username = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "username"));
		this.password = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "password"));
		this.domain = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "domain"));;

	}

}
