///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

package com.fulong.lyvc.message;

/**
 * MediaServerLogin
 * 
 * 龙驭视频会议系统 v3.0
 * 
 * 版权所有：北京中科辅龙计算机技术股份有限公司 2009
 * 
 * @author 李雄锋
 * 
 * 最后修改时间：2010-9-10
 */

public class MediaServerLogin extends BaseMessage{

	public static final int id = 38;

	public int udpPort;
	public int tcpPort;
	public String ip;
	
	public String toXML() {
		StringBuffer xml = new StringBuffer();
		xml.append("<lyvcmessage>");
		xml.append("<id>" + id + "</id>");
		xml.append("<_senderid>" + this.getSenderId() + "</_senderid>");
		xml.append("<_conferenceid>" + this.getConferenceId() + "</_conferenceid>");
		xml.append("<udpPort>" + this.udpPort + "</udpPort>");
		xml.append("<tcpPort>" + this.tcpPort + "</tcpPort>");
		xml.append("<ip>");
		if(this.ip != null) {
			xml.append(encodeHtmlEscape(this.ip));
		}
		xml.append("</ip>");
		xml.append("</lyvcmessage>");
		
		return xml.toString();
	}

	public void fromXML(String xmlString) throws MessageFormatException {
		String tagContent;
		
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_senderid");
		this.setSenderId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_conferenceid");
		this.setConferenceId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "udpPort");
		this.udpPort = Integer.parseInt(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "tcpPort");
		this.tcpPort = Integer.parseInt(tagContent);
		this.ip = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "ip"));
	}

}
