///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

package com.fulong.lyvc.message;

/**
 * RegisterUserResponse
 * 
 * 龙驭视频会议系统 v3.0
 * 
 * 版权所有：北京中科辅龙计算机技术股份有限公司 2009
 * 
 * @author 李雄锋
 * 
 * 最后修改时间：2010-9-10
 */

public class RegisterUserResponse extends BaseMessage{

	public static final int id = 195;

	public boolean bSuccessful;
	public String message;

	public String toXML() {
		StringBuffer xml = new StringBuffer();
		xml.append("<lyvcmessage>");
		xml.append("<id>" + id + "</id>");
		xml.append("<_senderid>" + this.getSenderId() + "</_senderid>");
		xml.append("<_conferenceid>" + this.getConferenceId() + "</_conferenceid>");
		xml.append("<bSuccessful>");
		if( this.bSuccessful){
			xml.append(1);
		} else {
			xml.append(0);
		}
		xml.append("</bSuccessful>");
		xml.append("<message>");
		if(this.message != null) {
			xml.append(encodeHtmlEscape(this.message));
		}
		xml.append("</message>");
		xml.append("</lyvcmessage>");
		
		return xml.toString();
	}

	public void fromXML(String xmlString) throws MessageFormatException {
		String tagContent;
		
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_senderid");
		this.setSenderId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_conferenceid");
		this.setConferenceId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "bSuccessful");
		if( tagContent.equals("0")) {
			this.bSuccessful = false;
		} else {
			this.bSuccessful = true;
		}
		this.message = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "message"));
	}

}
