///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

package com.fulong.lyvc.message;

/**
 * UserDetail
 * 
 * 龙驭视频会议系统 v3.0
 * 
 * 版权所有：北京中科辅龙计算机技术股份有限公司 2009
 * 
 * @author 李雄锋
 * 
 * 最后修改时间：2010-9-10
 */

public class UserDetail extends BaseMessage{

	public static final int id = 126;

	public int userRole;
	public String userId;
	public String userName;
	public String firstName;
	public String lastName;
	public String email;

	public String toXML() {
		StringBuffer xml = new StringBuffer();
		xml.append("<lyvcmessage>");
		xml.append("<id>" + id + "</id>");
		xml.append("<_senderid>" + this.getSenderId() + "</_senderid>");
		xml.append("<_conferenceid>" + this.getConferenceId() + "</_conferenceid>");
		xml.append("<userRole>" + this.userRole + "</userRole>");
		xml.append("<userId>" + this.userId + "</userId>");
		xml.append("<userName>");
		if(this.userName != null) {
			xml.append(encodeHtmlEscape(this.userName));
		}
		xml.append("</userName>");
		xml.append("<firstName>");
		if(this.firstName != null) {
			xml.append(encodeHtmlEscape(this.firstName));
		}
		xml.append("</firstName>");
		xml.append("<lastName>");
		if(this.lastName != null) {
			xml.append(encodeHtmlEscape(this.lastName));
		}
		xml.append("</lastName>");
		xml.append("<email>");
		if(this.email != null) {
			xml.append(encodeHtmlEscape(this.email));
		}
		xml.append("</email>");
		xml.append("</lyvcmessage>");
		
		return xml.toString();
	}

	public void fromXML(String xmlString) throws MessageFormatException {
		String tagContent;
		
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_senderid");
		this.setSenderId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "_conferenceid");
		this.setConferenceId(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "userRole");
		this.userRole = Integer.parseInt(tagContent);
		tagContent = BaseMessage.getStringBetweenTag(xmlString, "userId");
		this.userId = tagContent;
		this.userName = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "userName"));
		this.firstName = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "firstName"));
		this.lastName = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "lastName"));
		this.email = BaseMessage.decodeHtmlEscape(BaseMessage.getStringBetweenTag(xmlString, "email"));
	}

}
