insert into PROPERTY_DEFINITION (PKID, NODE_DEFINITION_ID, NAME, MULTIPLE, MIN_LENGTH, MAX_LENGTH, TYPE, ORDERNO, DESCRIPTION, EDITOR_TYPE, ENUM_ENTRY, REFERENCE_TYPE, DELETABLE, READ_ONLY, NODE_TYPE)
values ('templates', 'site-scheme', '使用模板', '0', -1, -1, 1, 8, null, null, null, null, '1', '0', null);
insert into PROPERTY_DEFINITION (PKID, NODE_DEFINITION_ID, NAME, MULTIPLE, MIN_LENGTH, MAX_LENGTH, TYPE, ORDERNO, DESCRIPTION, EDITOR_TYPE, ENUM_ENTRY, REFERENCE_TYPE, DELETABLE, READ_ONLY, NODE_TYPE)
values ('displayName', 'site-scheme', '显示名称', '0', -1, -1, 1, 1, null, null, null, null, '1', '0', null);
insert into PROPERTY_DEFINITION (PKID, NODE_DEFINITION_ID, NAME, MULTIPLE, MIN_LENGTH, MAX_LENGTH, TYPE, ORDERNO, DESCRIPTION, EDITOR_TYPE, ENUM_ENTRY, REFERENCE_TYPE, DELETABLE, READ_ONLY, NODE_TYPE)
values ('domain', 'site-scheme', '域名', '0', -1, -1, 1, 2, null, null, null, null, '1', '0', null);
insert into PROPERTY_DEFINITION (PKID, NODE_DEFINITION_ID, NAME, MULTIPLE, MIN_LENGTH, MAX_LENGTH, TYPE, ORDERNO, DESCRIPTION, EDITOR_TYPE, ENUM_ENTRY, REFERENCE_TYPE, DELETABLE, READ_ONLY, NODE_TYPE)
values ('navigateTemplates', 'site-scheme', '导航模板', '0', -1, -1, 1, 9, null, null, null, null, '1', '0', null);
insert into PROPERTY_DEFINITION (PKID, NODE_DEFINITION_ID, NAME, MULTIPLE, MIN_LENGTH, MAX_LENGTH, TYPE, ORDERNO, DESCRIPTION, EDITOR_TYPE, ENUM_ENTRY, REFERENCE_TYPE, DELETABLE, READ_ONLY, NODE_TYPE)
values ('prop1', 'site-scheme', 'liulei', '0', -1, -1, 1, 12, null, null, null, null, '1', '0', null);
insert into PROPERTY_DEFINITION (PKID, NODE_DEFINITION_ID, NAME, MULTIPLE, MIN_LENGTH, MAX_LENGTH, TYPE, ORDERNO, DESCRIPTION, EDITOR_TYPE, ENUM_ENTRY, REFERENCE_TYPE, DELETABLE, READ_ONLY, NODE_TYPE)
values ('prop04', 'site-scheme', '新属性02', '0', -1, -1, 1, 10, null, null, null, null, '1', '0', null);
insert into PROPERTY_DEFINITION (PKID, NODE_DEFINITION_ID, NAME, MULTIPLE, MIN_LENGTH, MAX_LENGTH, TYPE, ORDERNO, DESCRIPTION, EDITOR_TYPE, ENUM_ENTRY, REFERENCE_TYPE, DELETABLE, READ_ONLY, NODE_TYPE)
values ('prop078', 'site-scheme', '新属性033', '0', -1, -1, 1, 11, null, null, null, null, '1', '0', null);