<%@page contentType="text/html; charset=UTF-8"%>
<%@taglib uri="/WEB-INF/struts-bean.tld" prefix="bean"%>
<%@taglib uri="/WEB-INF/struts-logic.tld" prefix="logic"%>
<%@taglib uri="/WEB-INF/struts-html.tld" prefix="html"%>
<%@taglib uri="/WEB-INF/fulong.tld" prefix="fulong"%>
<%@page import="javax.portlet.PortletPreferences" %>
<bean:define id="propertyId" name="preferences" property="value(propertyId)" type="String"/>
<div id="div<%=(String)request.getAttribute("javax.portlet.id")%>" 
    	 style="<logic:notEmpty name="preferences" property="value(previewWidth)">width:<bean:write name="preferences" property="value(previewWidth)"/>;</logic:notEmpty> <logic:notEmpty name="preferences" property="value(previewHeight)">height:<bean:write name="preferences" property="value(previewHeight)"/>;</logic:notEmpty>" <logic:notEmpty name="preferences" property="value(previewStyle)">class="<bean:write name="preferences" property="value(previewStyle)"/>"</logic:notEmpty>>
    	 <img  style="<logic:notEmpty name="preferences" property="value(previewWidth)">width:<bean:write name="preferences" property="value(previewWidth)"/>;</logic:notEmpty> <logic:notEmpty name="preferences" property="value(previewHeight)">height:<bean:write name="preferences" property="value(previewHeight)"/>;</logic:notEmpty>" src="<logic:present name='pathValue'><bean:write name="pathValue" ignore="true"/></logic:present><logic:notPresent name='pathValue'><logic:empty name="preferences" property="value(defaultImage)">/ide/common/images/no_pic.gif</logic:empty><logic:notEmpty name="preferences" property="value(defaultImage)"><bean:define id="defaultImage" name="preferences" property="value(defaultImage)" type="String"/><%=defaultImage%></logic:notEmpty></logic:notPresent>" /></div>
 <!-- 以下4个TEXT标签用于存放该控件的file各属性 add by lkl 2010.4.21 -->
   <input type="hidden" id="txt_<%=(String)request.getAttribute("javax.portlet.id")%>1" <logic:notEmpty name="preferences" property="value(size)">value="<bean:write name="preferences" property="value(size)"/>"</logic:notEmpty>/>
   <input type="hidden" id="txt_<%=(String)request.getAttribute("javax.portlet.id")%>2"  value="<bean:write name="preferences" property="value(propertyId)" ignore="true"/>"/>
   <input type="hidden" id="txt_<%=(String)request.getAttribute("javax.portlet.id")%>3" <logic:notEmpty name="preferences" property="value(fileStyle)"> value="<bean:write name="preferences" property="value(fileStyle)"/>"</logic:notEmpty>/>
   <input type="hidden" id="txt_<%=(String)request.getAttribute("javax.portlet.id")%>4"  value="<%=(String)request.getAttribute("javax.portlet.id")%>"/>
  <span id="previewspan_<%=(String)request.getAttribute("javax.portlet.id")%>">  
<input type='file' <logic:notEmpty name="preferences" property="value(size)">size='<bean:write name="preferences" property="value(size)"/>'</logic:notEmpty> name='<bean:write name="preferences" property="value(propertyId)"/>' <logic:notEmpty name="preferences" property="value(fileStyle)">class='<bean:write name="preferences" property="value(fileStyle)"/>'</logic:notEmpty> <logic:notEmpty name="preferences" property="value(tabindex)">tabindex='<bean:write name="preferences" property="value(tabindex)"/>'</logic:notEmpty> onchange="singlepreview(div<%=(String)request.getAttribute("javax.portlet.id")%>, this.value,this,previewspan_<%=(String)request.getAttribute("javax.portlet.id")%>,txt_<%=(String)request.getAttribute("javax.portlet.id")%>1,txt_<%=(String)request.getAttribute("javax.portlet.id")%>2,txt_<%=(String)request.getAttribute("javax.portlet.id")%>3,txt_<%=(String)request.getAttribute("javax.portlet.id")%>4,'<bean:write name="preferences" property="value(maxSize)"/>','<logic:present name='pathValue'><bean:write name="pathValue" ignore="true"/></logic:present><logic:notPresent name='pathValue'><logic:empty name="preferences" property="value(defaultImage)">/ide/common/images/no_pic.gif</logic:empty><logic:notEmpty name="preferences" property="value(defaultImage)"><bean:define id="defaultImage" name="preferences" property="value(defaultImage)" type="String"/><%=defaultImage%></logic:notEmpty></logic:notPresent>')" />
</span>