package org.apache.jsp.service;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class smsSending_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(4);
    _jspx_dependants.add("/WEB-INF/struts-bean.tld");
    _jspx_dependants.add("/WEB-INF/struts-logic.tld");
    _jspx_dependants.add("/WEB-INF/struts-html.tld");
    _jspx_dependants.add("/WEB-INF/struts-tiles.tld");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>银河培训短信群发服务</title>\r\n");
      out.write("<base target=\"_self\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-cache, must-revalidate\" />\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"Wed, 26 Feb 1997 08:21:57 GMT\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/ide/service/styles.css\"/>\r\n");
      out.write("<script language=\"Javascript\" type=\"text/Javascript\" src=\"/ide/common/script/common.js.jsp\"></script>\r\n");
      out.write("<script language=\"Javascript\" type=\"text/Javascript\" src=\"/ide/service/scripts.js.jsp\"></script>\r\n");
      out.write("<script language=\"Javascript\" type=\"text/Javascript\" src=\"/ide/cms/classes/cmsdialog.js\"></script>\r\n");
      out.write("<script language=\"Javascript\" type=\"text/Javascript\" src=\"/ide/common/script/xmlhttp.js\"></script>\r\n");
      out.write("<script language=\"Javascript\" type=\"text/Javascript\" src=\"/ide/common/script/ajax.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("\t\tvar config = window.dialogArguments.parameters;\r\n");
      out.write("\t\tfunction doInit(){\r\n");
      out.write("\t\t\tconfig.populateForm(configForm);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction ok(){\r\n");
      out.write("\t\t\tconfig.updateFromForm(configForm);\r\n");
      out.write("\t\t\twindow.returnValue = config;\r\n");
      out.write("\t\t\twindow.close();   \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction selectCategory(objID,objName){\r\n");
      out.write("\t\t\t  var definition=CMSDialog.NodeDefinitionSelector();\r\n");
      out.write("\t\t\t\tif(definition!=null){\r\n");
      out.write("\t\t\t   if(definition.length>0){\r\n");
      out.write("\t\t\t       for(var j=0;j<definition.length;j++){\r\n");
      out.write("\t\t\t    \t   objID.value=definition[j].ID;\r\n");
      out.write("\t\t\t    \t   objName.value=definition[j].name;\r\n");
      out.write("\t\t\t       }\r\n");
      out.write("\t\t\t     }\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction selectProperty(categoryID,objID,objName,type){\r\n");
      out.write("\t\t\tif(categoryID==null){\r\n");
      out.write("\t\t\t\talert(\"请选择分类！\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    var result=CMSDialog.PropertyDefinitionSelector(categoryID,'',type);\r\n");
      out.write("\t\t\t    if(result!=null){\r\n");
      out.write("\t\t\t    \tobjID.value=result.ID;\r\n");
      out.write("\t\t\t    \tobjName.value=result.name;\r\n");
      out.write("\t\t\t      }\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"doInit()\">\r\n");
      out.write("<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"pannelDiv\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<select id=\"pannelSelect\" name=\"pannelSelect\" onchange=\"Service.SelectPanel(this)\" size=\"10\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">课程信息</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">日志信息</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">短信内容</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t<td id=\"tdFieldsets\" valign=\"top\" align=\"center\">\r\n");
      out.write("\t\t\t<form name=\"configForm\">\r\n");
      out.write("\t\t\t<fieldset class=\"fieldPanel\">\r\n");
      out.write("\t\t\t<div style=\"height: 200px;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>培训课程分类</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"trainingCategoryID\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" name=\"trainingCategoryName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectCategory(document.getElementById('trainingCategoryID'),document.getElementById('trainingCategoryName'))\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>课程代码</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"trainingCode\" name=\"trainingCode\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"trainingCodeName\" name=\"trainingCodeName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('trainingCategoryID').value,document.getElementById('trainingCode'),document.getElementById('trainingCodeName'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>课程名称</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"trainingName\" name=\"trainingName\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"trainingDisplayName\" name=\"trainingDisplayName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('trainingCategoryID').value,document.getElementById('trainingName'),document.getElementById('trainingDisplayName'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>参加学员用户名</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"usernameID\" name=\"usernameID\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"userName\" name=\"userName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('trainingCategoryID').value,document.getElementById('usernameID'),document.getElementById('userName'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>参加学员密码</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"passwordPropID\" name=\"passwordPropID\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"passwordPropName\" name=\"passwordPropName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('trainingCategoryID').value,document.getElementById('passwordPropID'),document.getElementById('passwordPropName'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>参加学员姓名</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"stuCommonname\" name=\"stuCommonname\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"commonname\" name=\"commonname\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('trainingCategoryID').value,document.getElementById('stuCommonname'),document.getElementById('commonname'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>参加学员手机号</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"phonePropID\" name=\"phonePropID\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"phonePropName\" name=\"phonePropName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('trainingCategoryID').value,document.getElementById('phonePropID'),document.getElementById('phonePropName'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>已发条数</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"sendedCount\" name=\"sendedCount\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"sendedCountName\" name=\"sendedCountName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('trainingCategoryID').value,document.getElementById('sendedCount'),document.getElementById('sendedCountName'),['3','4'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t\t<fieldset class=\"fieldPanel\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<div style=\"height: 200px;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>日志大纲</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"logCategoryID\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" name=\"logCategoryName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectCategory(document.getElementById('logCategoryID'),document.getElementById('logCategoryName'))\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>关联课程属性</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"trainingRefPropID\" name=\"trainingRefPropID\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"trainingRefPropDisplayName\" name=\"trainingRefPropDisplayName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('logCategoryID').value,document.getElementById('trainingRefPropID'),document.getElementById('trainingRefPropDisplayName'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>关联课程名称</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"trainingRefPropName\" name=\"trainingRefPropName\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"trainingRefProp\" name=\"trainingRefProp\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('logCategoryID').value,document.getElementById('trainingRefPropName'),document.getElementById('trainingRefProp'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>关联学员属性</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"stuRefPropID\" name=\"stuRefPropID\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"stuRefPropDisplayName\" name=\"stuRefPropDisplayName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('logCategoryID').value,document.getElementById('stuRefPropID'),document.getElementById('stuRefPropDisplayName'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>关联学员名称</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"stuRefPropName\" name=\"stuRefPropName\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"stuRefProp\" name=\"stuRefProp\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('logCategoryID').value,document.getElementById('stuRefPropName'),document.getElementById('stuRefProp'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>发送状态属性</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"statePropID\" name=\"statePropID\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"statePropName\" name=\"statePropName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('logCategoryID').value,document.getElementById('statePropID'),document.getElementById('statePropName'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>发送时间属性</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"sendTime\" name=\"sendTime\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"sendTimeName\" name=\"sendTimeName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('logCategoryID').value,document.getElementById('sendTime'),document.getElementById('sendTimeName'),['5'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>手机号码属性</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"mobilePropID\" name=\"mobilePropID\" />\r\n");
      out.write("\t\t\t    <input type=\"text\" id=\"mobilePropName\" name=\"mobilePropName\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t<button onclick=\"selectProperty(document.getElementById('logCategoryID').value,document.getElementById('mobilePropID'),document.getElementById('mobilePropName'),['1'])\">选择...</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t\t<fieldset class=\"fieldPanel\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<div style=\"height: 200px;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tr valign=\"top\">\r\n");
      out.write("\t\t\t<td>短信内容</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<textarea name=\"sendContent\" rows=\"15\" cols=\"30\"></textarea>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t<td>课程名用\"%courseName%\"，密码用\"%password%\"代替</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div id=\"toolbar\">\r\n");
      out.write("\t\t\t    <button onclick=\"ok()\" id=\"btnOK\">确定</button>\r\n");
      out.write("\t\t\t    <button onclick=\"window.close()\" id=\"btnCancel\">取消</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
