package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class script_js_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/javascript; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("// ////////////////////////////////////////////////////////////////////////////////////\n");
      out.write("// ///////以下是在portlet中共用的方法\n");
      out.write("/**\n");
      out.write(" * 选择样式 oInput：用于接收参数的控件，一般是Input控件 styleFilter：样式过滤器，即针对的标签\n");
      out.write(" */\n");
      out.write(" function doSelectStyle(oInput,styleFilter){\n");
      out.write("    \n");
      out.write("    var url = '/ide/site/css/css.jsp';\n");
      out.write("    var param=new Object();\n");
      out.write("    param.styleSheets= new Array();\n");
      out.write("    param.path=window.dialogArguments.page;\n");
      out.write("    var sheets=window.dialogArguments.styleSheets;\n");
      out.write("    param.selectedStyle=\"\"+oInput.value;\n");
      out.write("    param.filter=styleFilter;\n");
      out.write("    for(var i=0;i<sheets.length;i++){\n");
      out.write("      var href=sheets[i].href;\n");
      out.write("    /**\n");
      out.write("\t * luobin modified in 2010-03-18 bug 修改目的：下拉列表包含/portal/style.css.jsp\n");
      out.write("\t * 修改描述：!((href.indexOf('/fck_')>0)||(href.indexOf('/portal/')>0)||(href.length==0))改成\n");
      out.write("\t * !((href.indexOf('/fck_')>=0)||(href.indexOf('/portal/')>=0)||(href.length==0))\n");
      out.write("\t */\n");
      out.write("      if(!((href.indexOf('/fck_')>=0)||(href.indexOf('/portal/')>=0)||(href.length==0)))\n");
      out.write("         param.styleSheets.push(sheets[i]);\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    var value=showModalDialog(url, param, \"dialogWidth:470px;dialogHeight:460px;help:no;resizable:yes;status:no\");\n");
      out.write("    if( value != null && value != '' ){\n");
      out.write("    \tif(value == \":none\"){\n");
      out.write("    \t\toInput.value = \"\";\n");
      out.write("    \t}else{\n");
      out.write("    \t\toInput.value = value;\n");
      out.write("    \t}\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("/**\n");
      out.write(" * 插入占位符界面分页展示页面的选择Panel\n");
      out.write(" */\n");
      out.write("function selectPanelPortlet(oSelect){\n");
      out.write("var index=oSelect.options[oSelect.selectedIndex].value;\n");
      out.write("var portletType=document.getElementsByName(\"portletType\");\n");
      out.write("for(i=0;i<portletType.length;i++){\n");
      out.write("portletType[i].style.display=\"none\";\n");
      out.write("}\n");
      out.write("portletType[parseInt(index)].style.display=\"\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/**\n");
      out.write(" * 分页展示页面的选择Panel\n");
      out.write(" */\n");
      out.write("function selectPanel(oSelect){\n");
      out.write("var index=oSelect.options[oSelect.selectedIndex].value;\n");
      out.write("var fieldsets=oSelect.form.getElementsByTagName(\"fieldset\");\n");
      out.write("for(i=0;i<fieldsets.length;i++){\n");
      out.write("fieldsets[i].style.display=\"none\";\n");
      out.write("}\n");
      out.write("fieldsets[parseInt(index)].style.display=\"\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("function selectStyle(oInput){\n");
      out.write("doSelectStyle(oInput,null);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function showEditor(portletName,url){\n");
      out.write("var x=window.screenTop;\n");
      out.write("var y=window.screenLeft;\n");
      out.write("var ret=window.showModalDialog('/portal/modalWrapper.jsp?title='+encodeURIComponent(portletName)+'&url='+encodeURIComponent(url),'','dialogHeight:500px;dialogWidth:500px;status:no');\n");
      out.write("if(ret!=null){\n");
      out.write("  window.location.reload();\n");
      out.write("}\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/**\n");
      out.write(" * navigator/edit.jsp\n");
      out.write(" */\n");
      out.write("\n");
      out.write(" function selectAll(oSelect){\n");
      out.write("    oSelect.multiple=true;\n");
      out.write("    var obj=oSelect.options;\n");
      out.write("    for(var i=0;i<obj.length;i++)\n");
      out.write("    {\n");
      out.write("      obj.options[i].selected=true;\n");
      out.write("    }\n");
      out.write("  }\n");
      out.write("  function optionExists(value,oSelect){\n");
      out.write("   if(oSelect.options!=null)\n");
      out.write("    for(var j=0;j<oSelect.options.length;j++){\n");
      out.write("      if(oSelect.options[j].value==value)\n");
      out.write("      return true;\n");
      out.write("    }\n");
      out.write("    return false;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("\n");
      out.write("/**\n");
      out.write(" * 同步 隐藏域和 checkbox\n");
      out.write(" */\n");
      out.write("function syn_checkbox(oCheck,sName){\n");
      out.write(" oCheck.form.elements(sName).value=\"\"+oCheck.checked;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/**\n");
      out.write(" * field/edit.jsp\n");
      out.write(" */\n");
      out.write("\n");
      out.write("/**\n");
      out.write(" * 控制显示pannel；\n");
      out.write(" */\n");
      out.write("\n");
      out.write("\n");
      out.write("function doScroll(elem){\n");
      out.write("if(elem!=null){\n");
      out.write("var oElem=document.all(elem,0);\n");
      out.write("if(oElem!=null){\n");
      out.write("window.scrollTo(oElem.offsetLeft,oElem.offsetTop);\n");
      out.write("}\n");
      out.write("}\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function div_display(form){\n");
      out.write("\tportletId = form.id\n");
      out.write("\tif( form.selectItem.value==1 ) {\n");
      out.write("\t\t\t\teval(\"div1_\"+portletId)  .style.display=\"\";\n");
      out.write("\t\t\t\teval(\"div11_\"+portletId) .style.display=\"\";\n");
      out.write("\t\t\t\teval(\"div2_\"+portletId)  .style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div22_\"+portletId) .style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div3_\"+portletId)  .style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div33_\"+portletId) .style.display=\"none\";\n");
      out.write("\n");
      out.write("\t} else if(form.selectItem.value==2) {\n");
      out.write("\t\t\t\teval(\"div1_\"+portletId)  .style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div11_\"+portletId) .style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div2_\"+portletId)  .style.display=\"\";\n");
      out.write("\t\t\t\teval(\"div22_\"+portletId) .style.display=\"\";\n");
      out.write("\t\t\t\teval(\"div3_\"+portletId)  .style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div33_\"+portletId) .style.display=\"none\";\n");
      out.write("\n");
      out.write("\t\t\t\tsetFolderURL(form);\n");
      out.write("\t\t\t} else if(form.selectItem.value==3) {\n");
      out.write("\t\t\t\teval(\"div1_\"+portletId)  .style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div11_\"+portletId) .style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div2_\"+portletId)  .style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div22_\"+portletId) .style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div3_\"+portletId)  .style.display=\"\";\n");
      out.write("\t\t\t\teval(\"div33_\"+portletId) .style.display=\"\";\n");
      out.write("\n");
      out.write("\t\t\t\tsetContentURL(form);\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function div_auto_display(form){\n");
      out.write("\tportletId = form.id\n");
      out.write("\tif( form.auto.value==\"true\" ) {\n");
      out.write("\t\t\t\teval(\"div_1_\"+portletId).style.display=\"none\";\n");
      out.write("\t\t\t\teval(\"div_2_\"+portletId).style.display=\"none\";\n");
      out.write("\t} else {\n");
      out.write("\t\t\t\teval(\"div_1_\"+portletId).style.display=\"\";\n");
      out.write("\t\t\t\teval(\"div_2_\"+portletId).style.display=\"\";\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function setFolderURL(form){\n");
      out.write("contentFolderId = form.contentFolder.value;\n");
      out.write("form.url.value = form.path.value + \"/\" + contentFolderId + \"/index.fdp\";\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("function doPost(form,i){\n");
      out.write("form.pageNo.value =i;\n");
      out.write("form.submit();\n");
      out.write("}\n");
      out.write("function newSearch(form){\n");
      out.write("form.pageNo.value =1;\n");
      out.write("form.submit();\n");
      out.write("}\n");
      out.write("function setContentURL(form){\n");
      out.write("if (form.currentContent == null)\n");
      out.write("{\n");
      out.write("\treturn;\n");
      out.write("}\n");
      out.write("contentFolderId = form.content.value;\n");
      out.write("form.url.value = form.path.value + \"/\" + contentFolderId + \"/content.fdp?contentId=\" + GetRadioValue(form.currentContent);\n");
      out.write("}\n");
      out.write("function changeContentFolder(theForm){\n");
      out.write("// theForm.folder_id[0].value=theForm.folder_id[1].value;\n");
      out.write("\ttheForm.sub.value=0;\n");
      out.write("\ttheForm.submit();\n");
      out.write("}\n");
      out.write("function subForm(form){\n");
      out.write("\tform.sub.value=1;\n");
      out.write("}\n");
      out.write("function upload(form){\n");
      out.write("\tif(GetRadioValue(form.flag) ==\"2\"){\n");
      out.write("\tif(Trim(form.imgName.value) ==\"\"){\n");
      out.write("\t\talert(\"图片名称不能为空!\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\t}\n");
      out.write("\tif (GetRadioValue(form.flag)==\"1\"){\n");
      out.write("\tif(confirm('如果覆盖以前的的文件,以前应用这个文件的页面都会相应的改变。')){\n");
      out.write("\t}else{\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\t}\n");
      out.write("\tform.sub.value=2;\n");
      out.write("\treturn true;\n");
      out.write("}\n");
      out.write("function changeRule(form){\n");
      out.write("\tif (form.rule.value==\"custom\"){\n");
      out.write("\tform.contentFolderId.size=\"5\"\n");
      out.write("\tform.contentFolderId.multiple=\"true\"\n");
      out.write("\t}else{\n");
      out.write("\tform.contentFolderId.size=\"1\"\n");
      out.write("\tform.contentFolderId.multiple=\"\"\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("function div_auto_display_rt(form){\n");
      out.write("\tportletId = form.id;\n");
      out.write("\tif( form.type.value==\"auto\" ) {\n");
      out.write("\t\t\t\teval(\"div_\"+portletId).style.display=\"none\";\n");
      out.write("\t} else {\n");
      out.write("\t\t\t\teval(\"div_\"+portletId).style.display=\"\";\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("function common_image_selectImg(theForm, theImage){\n");
      out.write("theForm.source.value=theImage.alt;\n");
      out.write("theForm.all(\"previewImg\").src=theImage.src;\n");
      out.write("return false;\n");
      out.write("}\n");
      out.write("function nf_change(theForm){\n");
      out.write("theForm.sub.value=0;\n");
      out.write("theForm.submit();\n");
      out.write("}\n");
      out.write("function pc_change(theForm){\n");
      out.write("// if(theForm.source.options[theForm.source.selectedIndex].value==\"empty\")\n");
      out.write("theForm.sub.value=0;\n");
      out.write("theForm.submit();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function pc_submit(theForm){\n");
      out.write("if(theForm.source.options[theForm.source.selectedIndex].value==\"empty\"){\n");
      out.write("\tif (Trim(theForm.fileName.value)==\"\"){\n");
      out.write("\t\talert(\"名称不能为空！\")\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\ttheForm.source.options[theForm.source.selectedIndex].value=theForm.resourceFolderId.options[theForm.resourceFolderId.selectedIndex].value +\"/\" + theForm.fileName.value +\".jspf\";\n");
      out.write("\n");
      out.write("}\n");
      out.write("return true\n");
      out.write("}\n");
      out.write("\n");
      out.write("function review_submit(theForm){\n");
      out.write("if(theForm.forum.options[theForm.forum.selectedIndex].value==\"empty\"){\n");
      out.write("\tif (Trim(theForm.fileName.value)==\"\"){\n");
      out.write("\t\talert(\"名称不能为空！\")\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("return true\n");
      out.write("}\n");
      out.write("\n");
      out.write("function st_submit(form){\n");
      out.write("str=form.text.value;\n");
      out.write("str=str.replace(/</g,\"&lt\");\n");
      out.write("str=str.replace(/>/g,\"&gt\");\n");
      out.write("str=str.replace(/\\n/g,\"<br>\");\n");
      out.write("alert(str)\n");
      out.write("form.text.value=str;\n");
      out.write("}\n");
      out.write("function review_post_submit(theform){\n");
      out.write("\tif (Trim(theform.forumposttitle.value)==\"\"){\n");
      out.write("\t\talert(\"标题不能为空！\")\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("return true;\n");
      out.write("}\n");
      out.write("function static_select(oForm){\n");
      out.write("  var oSelect=oForm.elements(\"source\");\n");
      out.write("  if(oSelect.selectedIndex>0){\n");
      out.write("   var req=getXMLHttpRequest();\n");
      out.write("   var url=encodeURI(oSelect.options[oSelect.selectedIndex].title);\n");
      out.write("   var callback=function(){\n");
      out.write("       if((req.readystate==4)&&(req.status==200)){\n");
      out.write("       var newText=req.responseText;\n");
      out.write("          document.all(\"content\").value=newText;\n");
      out.write("          document.all(\"editor\").contentWindow.reloadHTML(newText);\n");
      out.write("       }\n");
      out.write("   }\n");
      out.write("   sendRequest(req,url,callback);\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("function static_submit(oForm){\n");
      out.write("oForm.submit();\n");
      out.write("}\n");
      out.write("function static_delete(submitter){\n");
      out.write("if(confirm(\"删除这个页面片断将使所有引用这个页面片断的页面无法正常显示，确认删除？\")){\n");
      out.write("var oSelect=submitter.form.elements(\"source\");\n");
      out.write("  if(oSelect.selectedIndex>0){\n");
      out.write("   var req=getXMLHttpRequest();\n");
      out.write("   var value=oSelect.options[oSelect.selectedIndex].value;\n");
      out.write("   var url=\"/ide/statics/deleteContents.do\";\n");
      out.write("   url=url+\"repositoryId=static&content=\"+encodeURIComponent(value);\n");
      out.write("   var callback=function(){\n");
      out.write("       if((req.readystate==4)&&(req.status==200)){\n");
      out.write("       oSelect.options.remove(oSelect.selectedIndex);\n");
      out.write("       oSelect.selectedIndex=0;\n");
      out.write("       document.all(\"editor\").contentWindow.reloadHTML(\"\");\n");
      out.write("       }\n");
      out.write("   }\n");
      out.write("   sendRequest(req,url,callback);\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("}\n");
      out.write("function static_create(submitter){\n");
      out.write("  document.all.editPanel.style.display=\"none\";\n");
      out.write("    document.all.createPanel.style.display=\"\";\n");
      out.write("    document.all(\"create\").value=\"true\";\n");
      out.write("}\n");
      out.write("function static_edit(submitter){\n");
      out.write("  document.all.editPanel.style.display=\"\";\n");
      out.write("    document.all.createPanel.style.display=\"none\";\n");
      out.write("    document.all(\"create\").value=\"false\";\n");
      out.write("}\n");
      out.write("function html_submit(oForm){\n");
      out.write("oForm.elements(\"text\").value=oForm.all(\"staticContentEditor\").innerHTML;\n");
      out.write("oForm.submit();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function portal_toggleSelect(selected){\n");
      out.write("  if(!enableToggle) return;\n");
      out.write("  selected.rows[0].style.display=\"\";\n");
      out.write("}\n");
      out.write("function portal_toggleUnSelect(selected){\n");
      out.write("  if(!enableToggle) return;\n");
      out.write("  selected.rows[0].style.display=\"none\";\n");
      out.write("}\n");
      out.write("\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
