<%@page contentType="text/html; charset=UTF-8"%><%@taglib uri="/WEB-INF/struts-bean.tld" prefix="bean"%><%@taglib uri="/WEB-INF/struts-logic.tld" prefix="logic"%><%@taglib uri="/WEB-INF/struts-html.tld" prefix="html"%><%@taglib uri="/WEB-INF/fulong.tld" prefix="fulong"%>
<object classid="clsid:6BF52A52-394A-11D3-B153-00C04F79FAA6" id="<bean:write name="contentId"/><bean:write name="preferences" property="value(field)"/>" <logic:notEmpty name="preferences" property="value(style)">class="<bean:write name="preferences" property="value(style)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(align)">align="<bean:write name="preferences" property="value(align)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(width)">width="<bean:write name="preferences" property="value(width)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(height)">height="<bean:write name="preferences" property="value(height)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(border)">border="<bean:write name="preferences" property="value(border)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(hspace)">hspace="<bean:write name="preferences" property="value(hspace)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(vspace)">vspace="<bean:write name="preferences" property="value(vspace)"/>"</logic:notEmpty>>
<logic:notEmpty name="pathValue"><param name="URL" value='<bean:write name="pathValue"/>'></logic:notEmpty>
<param name="playCount" value="<bean:write name="preferences" property="value(playCount)"/>">
<param name="autoStart" value="<logic:equal value="on" name="preferences" property="value(autoStart)">-1</logic:equal><logic:notEqual value="on" name="preferences" property="value(autoStart)">0</logic:notEqual>">
<param name="volume" value="<bean:write name="preferences" property="value(volume)"/>">
<param name="uiMode" value="<bean:write name="preferences" property="value(uiMode)"/>">
<param name="stretchToFit" value="<logic:equal value="on" name="preferences" property="value(stretchToFit)">-1</logic:equal><logic:notEqual value="on" name="preferences" property="value(stretchToFit)">0</logic:notEqual>">
<param name="windowlessVideo" value="<logic:equal value="on" name="preferences" property="value(windowlessVideo)">-1</logic:equal><logic:notEqual value="on" name="preferences" property="value(windowlessVideo)">0</logic:notEqual>">
<param name="fullScreen" value="<logic:notEqual value="false" name="preferences" property="value(fullScreen)">1</logic:notEqual><logic:equal value="false" name="preferences" property="value(fullScreen)">0</logic:equal>">
</object>
