<%@page contentType="text/html; charset=UTF-8"%><%@taglib uri="/WEB-INF/struts-bean.tld" prefix="bean"%><%@taglib uri="/WEB-INF/struts-html.tld" prefix="html"%><%@taglib uri="/WEB-INF/struts-logic.tld" prefix="logic"%><%@taglib uri="/WEB-INF/fulong-portal.tld" prefix="pt"%><pt:actionURL	portletMode="final" var="formURL"><pt:param name="portlet_action_name">saveNode</pt:param></pt:actionURL>
<logic:empty name="preferences" property="value(imgsrc)"><button type="button" id='<%=(String) request.getAttribute("javax.portlet.id")+"saveButton"%>' <logic:notEmpty name="preferences" property="value(name)">name="<bean:write name="preferences" property="value(name)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(style)">class="<bean:write name="preferences" property="value(style)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(size)">size="<bean:write name="preferences" property="value(size)"/>"</logic:notEmpty>
		onclick="return SavePortlet.singleSave('<bean:write name="preferences" property="value(hasIDParameter)"/>',this.form,'<%=formURL%>','<bean:write name="preferences" property="value(saveLimit)"/>',
<logic:present  name="com.fulong.longcon.Content">
'<bean:write name="com.fulong.longcon.Content" property="ID"/>'
</logic:present>
<logic:notPresent  name="com.fulong.longcon.Content">
null
</logic:notPresent>
,'<%=(String) request.getAttribute("javax.portlet.id")%>')"
<logic:notEmpty name="preferences" property="value(size)">size="<bean:write name="preferences" property="value(size)"/>"</logic:notEmpty>><logic:notEmpty
		name="preferences" property="value(value)"><bean:write name="preferences" property="value(value)" /></logic:notEmpty></button></logic:empty><logic:notEmpty name="preferences" property="value(imgsrc)">
	<image  id='<%=(String) request.getAttribute("javax.portlet.id")+"saveButton"%>' <logic:notEmpty name="preferences" property="value(name)">name="<bean:write name="preferences" property="value(name)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(imgstyle)">class="<bean:write name="preferences" property="value(imgstyle)"/>"</logic:notEmpty>
		<logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty>
		<logic:present  name="com.fulong.longcon.Content"> onclick="return SavePortlet.singleSave('<bean:write name="preferences" property="value(hasIDParameter)"/>',this.nextSibling.form,'<%=formURL%>','<bean:write name="preferences" property="value(saveLimit)"/>','<bean:write name="com.fulong.longcon.Content" property="ID"/>','<%=(String) request.getAttribute("javax.portlet.id")%>');return false;" 
</logic:present><logic:notPresent  name="com.fulong.longcon.Content"> onclick="return SavePortlet.singleSave('<bean:write name="preferences" property="value(hasIDParameter)"/>',this.nextSibling.form,'<%=formURL%>','<bean:write name="preferences" property="value(saveLimit)"/>',null,'<%=(String) request.getAttribute("javax.portlet.id")%>','<bean:write name="preferences" property="value(value)"/>');" </logic:notPresent><logic:notEmpty name="preferences" property="value(imgtitle)">title="<bean:write name="preferences" property="value(imgtitle)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(imgsrc)">src="<bean:write name="preferences" property="value(imgsrc)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(imghwidth)">width="<bean:write name="preferences" property="value(imgwidth)"/>"</logic:notEmpty>		<logic:notEmpty name="preferences" property="value(imgheight)">height="<bean:write name="preferences" property="value(imgheight)"/>"</logic:notEmpty> /><button id='<%=(String) request.getAttribute("javax.portlet.id")%>hiddenButton' style="display:none;"></button></logic:notEmpty>