<%@page contentType="text/html; charset=UTF-8"%><%@taglib uri="/WEB-INF/struts-bean.tld" prefix="bean"%><%@taglib uri="/WEB-INF/struts-logic.tld" prefix="logic"%><%@taglib uri="/WEB-INF/struts-html.tld" prefix="html"%><%@taglib uri="/WEB-INF/fulong-portal.tld" prefix="pt"%>
<bean:define id="preferences" name="preferences" type="javax.portlet.PortletPreferences"/>
<logic:notEqual value="on"  name="preferences" property="value(showHref)">
<logic:empty name="preferences" property="value(imgsrc)">
<%
String gotoBack = preferences.getValue("gotoBack", "false");
if(gotoBack.equals("false")){%>
<logic:equal value="on"  name="preferences" property="value(noParameter)"><button type="reset" <logic:notEmpty name="preferences" property="value(style)">class="<bean:write name="preferences" property="value(style)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(size)">size="<bean:write name="preferences" property="value(size)"/>"</logic:notEmpty> onclick="document.location='<bean:write name="preferences" property="value(channel)"/>'"><bean:write name="preferences" property="value(value)"/></button></logic:equal>
<logic:equal value="false"  name="preferences" property="value(noParameter)"><button type="reset" <logic:notEmpty name="preferences" property="value(style)">class="<bean:write name="preferences" property="value(style)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(size)">size="<bean:write name="preferences" property="value(size)"/>"</logic:notEmpty> onclick="document.location='<bean:write name="preferences" property="value(channel)"/><logic:notEmpty name="preferences" property="value(propertyId)"><logic:present name="paramet">?<bean:write name="preferences" property="value(propertyId)"/>=<bean:write name="paramet" ignore="true"/></logic:present><logic:notEmpty name="preferences" property="value(propertyId2)">&<bean:write name="preferences" property="value(propertyId2)"/>=<bean:write name="paramet" ignore="true"/></logic:notEmpty></logic:notEmpty><logic:empty name="preferences" property="value(propertyId)">?<bean:write name="paramet" ignore="true"/></logic:empty>'"   <logic:notEmpty name="preferences" property="value(size)">size="<bean:write name="preferences" property="value(size)"/>"</logic:notEmpty>><bean:write name="preferences" property="value(value)"/></button></logic:equal>
<%}else{%>
<button type="reset" <logic:notEmpty name="preferences" property="value(style)">class="<bean:write name="preferences" property="value(style)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(size)">size="<bean:write name="preferences" property="value(size)"/>"</logic:notEmpty> onclick="window.history.go(-1)"><bean:write name="preferences" property="value(value)"/></button>
<%}%>
</logic:empty>
<logic:notEmpty name="preferences" property="value(imgsrc)">
<%
String gotoBack = preferences.getValue("gotoBack", "false");
if(gotoBack.equals("false")){%>
<logic:equal value="on"  name="preferences" property="value(noParameter)">
<img <logic:notEmpty name="preferences" property="value(imgstyle)">class="<bean:write name="preferences" property="value(imgstyle)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty> onclick="document.location='<bean:write name="preferences" property="value(channel)"/>'"<logic:notEmpty name="preferences" property="value(imgsrc)">src="<bean:write name="preferences" property="value(imgsrc)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(imghwidth)">width="<bean:write name="preferences" property="value(imgwidth)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(imgheight)">height="<bean:write name="preferences" property="value(imgheight)"/>"</logic:notEmpty>/></logic:equal>
<logic:equal value="false"  name="preferences" property="value(noParameter)">
<img <logic:notEmpty name="preferences" property="value(imgstyle)">class="<bean:write name="preferences" property="value(imgstyle)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty> onclick="document.location='<bean:write name="preferences" property="value(channel)"/><logic:notEmpty name="preferences" property="value(propertyId)"><logic:present name="paramet">?<bean:write name="preferences" property="value(propertyId)"/>=<bean:write name="paramet" ignore="true"/></logic:present><logic:notEmpty name="preferences" property="value(propertyId2)">&<bean:write name="preferences" property="value(propertyId2)"/>=<bean:write name="paramet" ignore="true"/></logic:notEmpty></logic:notEmpty><logic:empty name="preferences" property="value(propertyId)">?<bean:write name="paramet" ignore="true"/></logic:empty>'"<logic:notEmpty name="preferences" property="value(imgsrc)">src="<bean:write name="preferences" property="value(imgsrc)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(imghwidth)">width="<bean:write name="preferences" property="value(imgwidth)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(imgheight)">height="<bean:write name="preferences" property="value(imgheight)"/>"</logic:notEmpty>/></logic:equal>
<%}else{%>
<img <logic:notEmpty name="preferences" property="value(imgstyle)">class="<bean:write name="preferences" property="value(imgstyle)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty> onclick="window.history.go(-1)" <logic:notEmpty name="preferences" property="value(imgsrc)">src="<bean:write name="preferences" property="value(imgsrc)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(imghwidth)">width="<bean:write name="preferences" property="value(imgwidth)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(imgheight)">height="<bean:write name="preferences" property="value(imgheight)"/>"</logic:notEmpty>/>
<%}%>
</logic:notEmpty>
</logic:notEqual>
<logic:equal value="on"  name="preferences" property="value(showHref)">
<%
String gotoBack = preferences.getValue("gotoBack", "false");
if(gotoBack.equals("false")){%>
<logic:equal value="on"  name="preferences" property="value(noParameter)">
<a href='<bean:write name="preferences" property="value(channel)"/>' <logic:notEmpty name="preferences" property="value(style)">class="<bean:write name="preferences" property="value(style)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty>><bean:write name="preferences" property="value(value)"/>
</a>
</logic:equal>
<logic:equal value="false"  name="preferences" property="value(noParameter)">
<a href='<bean:write name="preferences" property="value(channel)"/><logic:notEmpty name="preferences" property="value(propertyId)"><logic:present name="paramet">?<bean:write name="preferences" property="value(propertyId)"/>=<bean:write name="paramet" ignore="true"/></logic:present><logic:notEmpty name="preferences" property="value(propertyId2)">&<bean:write name="preferences" property="value(propertyId2)"/>=<bean:write name="paramet" ignore="true"/></logic:notEmpty></logic:notEmpty><logic:empty name="preferences" property="value(propertyId)">?<bean:write name="paramet" ignore="true"/></logic:empty>' <logic:notEmpty name="preferences" property="value(style)">class="<bean:write name="preferences" property="value(style)"/>"</logic:notEmpty><logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty>><bean:write name="preferences" property="value(value)"/>
</a>
</logic:equal>
<%}else{%>
<a href="javascript:window.history.go(-1)" <logic:notEmpty name="preferences" property="value(style)">class="<bean:write name="preferences" property="value(style)"/>"</logic:notEmpty> <logic:notEmpty name="preferences" property="value(tabindex)">tabindex="<bean:write name="preferences" property="value(tabindex)"/>"</logic:notEmpty>><bean:write name="preferences" property="value(value)"/>
</a>
<%}%>
</logic:equal>