///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "AddContact.h"

string LyvcMessage::AddContact::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<isCommon>";
	_snprintf(buffer, BUFFERSIZE, "%d", this->isCommon);
	xml = xml + buffer;
	xml = xml + "</isCommon>";
	xml = xml + "<status>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->status);
	xml = xml + buffer;
	xml = xml + "</status>";
	xml = xml + "<groupId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->groupId);
	xml = xml + buffer;
	xml = xml + "</groupId>";
	xml = xml + "<contactId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->contactId);
	xml = xml + buffer;
	xml = xml + "</contactId>";
	xml = xml + "<name>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->name);
	xml = xml + "</name>";
	xml = xml + "<email>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->email);
	xml = xml + "</email>";
	xml = xml + "<firstName>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->firstName);
	xml = xml + "</firstName>";
	xml = xml + "<lastName>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->lastName);
	xml = xml + "</lastName>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::AddContact::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "isCommon");
	if(tagContent == ""){
		return false;
	}
	this->isCommon = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "status");
	if(tagContent == ""){
		return false;
	}
	this->status = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "groupId");
	if(tagContent == ""){
		return false;
	}
	this->groupId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "contactId");
	if(tagContent == ""){
		return false;
	}
	this->contactId = _atoi64(tagContent.c_str());
	this->name = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "name"));
	this->email = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "email"));
	this->firstName = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "firstName"));
	this->lastName = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "lastName"));
	return true;
}


