///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "AddConference.h"

string LyvcMessage::AddConference::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<isStarted>";
	_snprintf(buffer, BUFFERSIZE, "%d", this->isStarted);
	xml = xml + buffer;
	xml = xml + "</isStarted>";
	xml = xml + "<isEnded>";
	_snprintf(buffer, BUFFERSIZE, "%d", this->isEnded);
	xml = xml + buffer;
	xml = xml + "</isEnded>";
	xml = xml + "<startTime>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->startTime*1000);
	xml = xml + buffer;
	xml = xml + "</startTime>";
	xml = xml + "<endTime>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->endTime*1000);
	xml = xml + buffer;
	xml = xml + "</endTime>";
	xml = xml + "<creatorId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->creatorId);
	xml = xml + buffer;
	xml = xml + "</creatorId>";
	xml = xml + "<conId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->conId);
	xml = xml + buffer;
	xml = xml + "</conId>";
	xml = xml + "<conModelId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->conModelId);
	xml = xml + buffer;
	xml = xml + "</conModelId>";
	xml = xml + "<conName>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->conName);
	xml = xml + "</conName>";
	xml = xml + "<conDesc>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->conDesc);
	xml = xml + "</conDesc>";
	xml = xml + "<conFilesDesc>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->conFilesDesc);
	xml = xml + "</conFilesDesc>";
	xml = xml + "<conFilesURL>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->conFilesURL);
	xml = xml + "</conFilesURL>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::AddConference::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "isStarted");
	if(tagContent == ""){
		return false;
	}
	this->isStarted = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "isEnded");
	if(tagContent == ""){
		return false;
	}
	this->isEnded = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "startTime");
	if(tagContent == ""){
		return false;
	}
	this->startTime = _atoi64(tagContent.c_str())/1000;
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "endTime");
	if(tagContent == ""){
		return false;
	}
	this->endTime = _atoi64(tagContent.c_str())/1000;
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "creatorId");
	if(tagContent == ""){
		return false;
	}
	this->creatorId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "conId");
	if(tagContent == ""){
		return false;
	}
	this->conId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "conModelId");
	if(tagContent == ""){
		return false;
	}
	this->conModelId = _atoi64(tagContent.c_str());
	this->conName = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "conName"));
	this->conDesc = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "conDesc"));
	this->conFilesDesc = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "conFilesDesc"));
	this->conFilesURL = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "conFilesURL"));
	return true;
}


