///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "AddGroup.h"

string LyvcMessage::AddGroup::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<isCommon>";
	_snprintf(buffer, BUFFERSIZE, "%d", this->isCommon);
	xml = xml + buffer;
	xml = xml + "</isCommon>";
	xml = xml + "<groupId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->groupId);
	xml = xml + buffer;
	xml = xml + "</groupId>";
	xml = xml + "<parentGroupId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->parentGroupId);
	xml = xml + buffer;
	xml = xml + "</parentGroupId>";
	xml = xml + "<name>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->name);
	xml = xml + "</name>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::AddGroup::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "isCommon");
	if(tagContent == ""){
		return false;
	}
	this->isCommon = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "groupId");
	if(tagContent == ""){
		return false;
	}
	this->groupId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "parentGroupId");
	if(tagContent == ""){
		return false;
	}
	this->parentGroupId = _atoi64(tagContent.c_str());
	this->name = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "name"));
	return true;
}


