///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef AddGroup_H
#define AddGroup_H

#include "BaseMessage.h"

namespace LyvcMessage {

class AddGroup : public BaseMessage{

	public:
		static const id = 113;
		bool isCommon;
		__int64 groupId;
		__int64 parentGroupId;
		string name;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

