///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef Advertizement_H
#define Advertizement_H

#include "BaseMessage.h"

namespace LyvcMessage {

class Advertizement : public BaseMessage{

	public:
		static const id = 187;
		string homepage;
		string mainframe;
		string roomframe;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

