///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef AgreeVideo_H
#define AgreeVideo_H

#include "BaseMessage.h"

namespace LyvcMessage {

class AgreeVideo : public BaseMessage{

	public:
		static const id = 78;
		__int32 width;
		__int32 height;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;
		__int64 videoSenderId;
		string TKLHead;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

