///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef AgreeInviteDesktop_H
#define AgreeInviteDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class AgreeInviteDesktop : public BaseMessage{

	public:
		static const id = 100;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

