///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef AgreeControlDesktop_H
#define AgreeControlDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class AgreeControlDesktop : public BaseMessage{

	public:
		static const id = 98;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

