///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef AgreeReceiveFile_H
#define AgreeReceiveFile_H

#include "BaseMessage.h"

namespace LyvcMessage {

class AgreeReceiveFile : public BaseMessage{

	public:
		static const id = 162;
		__int64 receiverId;
		string fullFileName;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

