///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ApplyAudio_H
#define ApplyAudio_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ApplyAudio : public BaseMessage{

	public:
		static const id = 72;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

