///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ApplyControlDesktop_H
#define ApplyControlDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ApplyControlDesktop : public BaseMessage{

	public:
		static const id = 101;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

