///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ApplyDesktop_H
#define ApplyDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ApplyDesktop : public BaseMessage{

	public:
		static const id = 102;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

