///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ApplySpeak_H
#define ApplySpeak_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ApplySpeak : public BaseMessage{

	public:
		static const id = 171;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

