///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ApplyContact_H
#define ApplyContact_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ApplyContact : public BaseMessage{

	public:
		static const id = 115;
		__int64 receiverId;
		string name;
		__int64 groupId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

