///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ApplyVideo_H
#define ApplyVideo_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ApplyVideo : public BaseMessage{

	public:
		static const id = 77;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

