///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef CameraZoomOut_H
#define CameraZoomOut_H

#include "BaseMessage.h"

namespace LyvcMessage {

class CameraZoomOut : public BaseMessage{

	public:
		static const id = 179;
		__int32 commPort;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

