///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef CameraZoomIn_H
#define CameraZoomIn_H

#include "BaseMessage.h"

namespace LyvcMessage {

class CameraZoomIn : public BaseMessage{

	public:
		static const id = 178;
		__int32 commPort;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

