///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef CameraMoveUp_H
#define CameraMoveUp_H

#include "BaseMessage.h"

namespace LyvcMessage {

class CameraMoveUp : public BaseMessage{

	public:
		static const id = 176;
		__int32 commPort;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

