///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef CameraMoveRight_H
#define CameraMoveRight_H

#include "BaseMessage.h"

namespace LyvcMessage {

class CameraMoveRight : public BaseMessage{

	public:
		static const id = 175;
		__int32 commPort;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

