///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ChangeUserInfo_H
#define ChangeUserInfo_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ChangeUserInfo : public BaseMessage{

	public:
		static const id = 193;
		__int64 userId;
		string userName;
		string password;
		string firstName;
		string lastName;
		string email;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

