///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ChangeGroupName_H
#define ChangeGroupName_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ChangeGroupName : public BaseMessage{

	public:
		static const id = 123;
		__int64 groupId;
		string newName;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

