///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "CheckVersion.h"

string LyvcMessage::CheckVersion::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<domain>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->domain);
	xml = xml + "</domain>";
	xml = xml + "<bHasNewVersion>";
	_snprintf(buffer, BUFFERSIZE, "%d", this->bHasNewVersion);
	xml = xml + buffer;
	xml = xml + "</bHasNewVersion>";
	xml = xml + "<bNeedUpdate>";
	_snprintf(buffer, BUFFERSIZE, "%d", this->bNeedUpdate);
	xml = xml + buffer;
	xml = xml + "</bNeedUpdate>";
	xml = xml + "<version>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->version);
	xml = xml + buffer;
	xml = xml + "</version>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::CheckVersion::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "bHasNewVersion");
	if(tagContent == ""){
		return false;
	}
	this->bHasNewVersion = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "bNeedUpdate");
	if(tagContent == ""){
		return false;
	}
	this->bNeedUpdate = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "version");
	if(tagContent == ""){
		return false;
	}
	this->version = atoi(tagContent.c_str());
	this->domain = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "domain"));
	return true;
}


