///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef CheckVersion_H
#define CheckVersion_H

#include "BaseMessage.h"

namespace LyvcMessage {

class CheckVersion : public BaseMessage{

	public:
		static const id = 182;
		bool bHasNewVersion;
		bool bNeedUpdate;
		__int32 version;
		string domain;	//”Ú√˚

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

