///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "ConferenceNotice.h"

string LyvcMessage::ConferenceNotice::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<sendDate>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->sendDate*1000);
	xml = xml + buffer;
	xml = xml + "</sendDate>";
	xml = xml + "<conferenceId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->conferenceId);
	xml = xml + buffer;
	xml = xml + "</conferenceId>";
	xml = xml + "<receiverId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->receiverId);
	xml = xml + buffer;
	xml = xml + "</receiverId>";
	xml = xml + "<title>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->title);
	xml = xml + "</title>";
	xml = xml + "<content>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->content);
	xml = xml + "</content>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::ConferenceNotice::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "sendDate");
	if(tagContent == ""){
		return false;
	}
	this->sendDate = _atoi64(tagContent.c_str())/1000;
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "conferenceId");
	if(tagContent == ""){
		return false;
	}
	this->conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "receiverId");
	if(tagContent == ""){
		return false;
	}
	this->receiverId = _atoi64(tagContent.c_str());
	this->title = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "title"));
	this->content = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "content"));
	return true;
}


