///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ConferenceNotice_H
#define ConferenceNotice_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ConferenceNotice : public BaseMessage{

	public:
		static const id = 191;
		__time64_t sendDate;
		__int64 conferenceId;
		__int64 receiverId;
		string title;
		string content;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

