///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ConferenceFinish_H
#define ConferenceFinish_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ConferenceFinish : public BaseMessage{

	public:
		static const id = 157;
		__int64 conId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

