///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef CopyContact_H
#define CopyContact_H

#include "BaseMessage.h"

namespace LyvcMessage {

class CopyContact : public BaseMessage{

	public:
		static const id = 186;
		bool bIsGroupId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

