///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef CreateInstantConference_H
#define CreateInstantConference_H

#include "BaseMessage.h"

namespace LyvcMessage {

class CreateInstantConference : public BaseMessage{

	public:
		static const id = 134;
		string participants;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

