///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef DefaultGroupId_H
#define DefaultGroupId_H

#include "BaseMessage.h"

namespace LyvcMessage {

class DefaultGroupId : public BaseMessage{

	public:
		static const id = 125;
		__int64 defaultGroupId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

