///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef DesktopClientMouseEvent_H
#define DesktopClientMouseEvent_H

#include "BaseMessage.h"

namespace LyvcMessage {

class DesktopClientMouseEvent : public BaseMessage{

	public:
		static const id = 86;
		__int32 buttonMask;
		__int32 x;
		__int32 y;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

