///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "DesktopClientMouseEvent.h"

string LyvcMessage::DesktopClientMouseEvent::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<buttonMask>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->buttonMask);
	xml = xml + buffer;
	xml = xml + "</buttonMask>";
	xml = xml + "<x>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->x);
	xml = xml + buffer;
	xml = xml + "</x>";
	xml = xml + "<y>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->y);
	xml = xml + buffer;
	xml = xml + "</y>";
	xml = xml + "<receiverId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->receiverId);
	xml = xml + buffer;
	xml = xml + "</receiverId>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::DesktopClientMouseEvent::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "buttonMask");
	if(tagContent == ""){
		return false;
	}
	this->buttonMask = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "x");
	if(tagContent == ""){
		return false;
	}
	this->x = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "y");
	if(tagContent == ""){
		return false;
	}
	this->y = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "receiverId");
	if(tagContent == ""){
		return false;
	}
	this->receiverId = _atoi64(tagContent.c_str());
	return true;
}


