///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef DesktopClientKeyEvent_H
#define DesktopClientKeyEvent_H

#include "BaseMessage.h"

namespace LyvcMessage {

class DesktopClientKeyEvent : public BaseMessage{

	public:
		static const id = 94;
		bool downFlag;
		__int32 key;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

