///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef DesktopClientRequestUpdate_H
#define DesktopClientRequestUpdate_H

#include "BaseMessage.h"

namespace LyvcMessage {

class DesktopClientRequestUpdate : public BaseMessage{

	public:
		static const id = 88;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

