///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef EvaluateVideoQuality_H
#define EvaluateVideoQuality_H

#include "BaseMessage.h"

namespace LyvcMessage {

class EvaluateVideoQuality : public BaseMessage{

	public:
		static const id = 183;
		__int32 quality;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

