///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef GetConferenceModelTable_H
#define GetConferenceModelTable_H

#include "BaseMessage.h"

namespace LyvcMessage {

class GetConferenceModelTable : public BaseMessage{

	public:
		static const id = 52;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

