///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef GetMediaServerAddress_H
#define GetMediaServerAddress_H

#include "BaseMessage.h"

namespace LyvcMessage {

class GetMediaServerAddress : public BaseMessage{

	public:
		static const id = 70;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

