///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef GetPendingMessageList_H
#define GetPendingMessageList_H

#include "BaseMessage.h"

namespace LyvcMessage {

class GetPendingMessageList : public BaseMessage{

	public:
		static const id = 155;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

