///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef InviteDesktop_H
#define InviteDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class InviteDesktop : public BaseMessage{

	public:
		static const id = 103;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

