///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "InviteConference.h"

string LyvcMessage::InviteConference::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<conferenceId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->conferenceId);
	xml = xml + buffer;
	xml = xml + "</conferenceId>";
	xml = xml + "<contactId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->contactId);
	xml = xml + buffer;
	xml = xml + "</contactId>";
	xml = xml + "<holderId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->holderId);
	xml = xml + buffer;
	xml = xml + "</holderId>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::InviteConference::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "conferenceId");
	if(tagContent == ""){
		return false;
	}
	this->conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "contactId");
	if(tagContent == ""){
		return false;
	}
	this->contactId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "holderId");
	if(tagContent == ""){
		return false;
	}
	this->holderId = _atoi64(tagContent.c_str());
	return true;
}


