///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef InviteConference_H
#define InviteConference_H

#include "BaseMessage.h"

namespace LyvcMessage {

class InviteConference : public BaseMessage{

	public:
		static const id = 127;
		__int64 conferenceId;
		__int64 contactId;
		__int64 holderId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

