///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef JoinConferenceResponse_H
#define JoinConferenceResponse_H

#include "BaseMessage.h"

namespace LyvcMessage {

class JoinConferenceResponse : public BaseMessage{

	public:
		static const id = 64;
		__int64 conId;
		__int64 roleId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

