///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef JoinConference_H
#define JoinConference_H

#include "BaseMessage.h"

namespace LyvcMessage {

class JoinConference : public BaseMessage{

	public:
		static const id = 63;
		__int32 avCompressionCardChannelNumber;
		__int64 conId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

