///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef KeepAlive_H
#define KeepAlive_H

#include "BaseMessage.h"

namespace LyvcMessage {

class KeepAlive : public BaseMessage{

	public:
		static const id = 198;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

