///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef KickDuplicateLogin_H
#define KickDuplicateLogin_H

#include "BaseMessage.h"

namespace LyvcMessage {

class KickDuplicateLogin : public BaseMessage{

	public:
		static const id = 189;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

