///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "Login.h"

string LyvcMessage::Login::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<domain>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->domain);
	xml = xml + "</domain>";
	xml = xml + "<avCompressionCardChannelNumber>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->avCompressionCardChannelNumber);
	xml = xml + buffer;
	xml = xml + "</avCompressionCardChannelNumber>";
	xml = xml + "<username>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->username);
	xml = xml + "</username>";
	xml = xml + "<password>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->password);
	xml = xml + "</password>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::Login::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "avCompressionCardChannelNumber");
	if(tagContent == ""){
		return false;
	}
	this->avCompressionCardChannelNumber = atoi(tagContent.c_str());
	this->username = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "username"));
	this->password = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "password"));
	this->domain = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "domain"));
	return true;
}


