///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef LoginSuccessfully_H
#define LoginSuccessfully_H

#include "BaseMessage.h"

namespace LyvcMessage {

class LoginSuccessfully : public BaseMessage{

	public:
		static const id = 199;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

