///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "MediaServerAddress.h"

string LyvcMessage::MediaServerAddress::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<tcpport>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->tcpport);
	xml = xml + buffer;
	xml = xml + "</tcpport>";
	xml = xml + "<udpport>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->udpport);
	xml = xml + buffer;
	xml = xml + "</udpport>";
	xml = xml + "<host>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->host);
	xml = xml + "</host>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::MediaServerAddress::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "tcpport");
	if(tagContent == ""){
		return false;
	}
	this->tcpport = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "udpport");
	if(tagContent == ""){
		return false;
	}
	this->udpport = atoi(tagContent.c_str());
	this->host = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "host"));
	return true;
}


