///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef MediaServerLogin_H
#define MediaServerLogin_H

#include "BaseMessage.h"

namespace LyvcMessage {

class MediaServerLogin : public BaseMessage{

	public:
		static const id = 38;
		__int32 udpPort;
		__int32 tcpPort;
		string ip;
		string domain;	//”Ú√˚

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

