///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef MediaServerAddress_H
#define MediaServerAddress_H

#include "BaseMessage.h"

namespace LyvcMessage {

class MediaServerAddress : public BaseMessage{

	public:
		static const id = 71;
		__int32 tcpport;
		__int32 udpport;
		string host;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

