///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "MoveContactToGroup.h"

string LyvcMessage::MoveContactToGroup::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<oldGroupId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->oldGroupId);
	xml = xml + buffer;
	xml = xml + "</oldGroupId>";
	xml = xml + "<newGroupId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->newGroupId);
	xml = xml + buffer;
	xml = xml + "</newGroupId>";
	xml = xml + "<contactId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->contactId);
	xml = xml + buffer;
	xml = xml + "</contactId>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::MoveContactToGroup::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "oldGroupId");
	if(tagContent == ""){
		return false;
	}
	this->oldGroupId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "newGroupId");
	if(tagContent == ""){
		return false;
	}
	this->newGroupId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "contactId");
	if(tagContent == ""){
		return false;
	}
	this->contactId = _atoi64(tagContent.c_str());
	return true;
}


