///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef MoveContactToGroup_H
#define MoveContactToGroup_H

#include "BaseMessage.h"

namespace LyvcMessage {

class MoveContactToGroup : public BaseMessage{

	public:
		static const id = 116;
		__int64 oldGroupId;
		__int64 newGroupId;
		__int64 contactId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

