///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef NotifyMediaServerUserQuitConference_H
#define NotifyMediaServerUserQuitConference_H

#include "BaseMessage.h"

namespace LyvcMessage {

class NotifyMediaServerUserQuitConference : public BaseMessage{

	public:
		static const id = 197;
		__int64 userId;
		__int64 confId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

