///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef NotifyMediaServerAddDesktop_H
#define NotifyMediaServerAddDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class NotifyMediaServerAddDesktop : public BaseMessage{

	public:
		static const id = 147;
		bool isAgreeInvite;
		__int64 fromUserId;
		__int64 toUserId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

