///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef NotifyMediaServerRemoveDesktop_H
#define NotifyMediaServerRemoveDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class NotifyMediaServerRemoveDesktop : public BaseMessage{

	public:
		static const id = 148;
		__int64 fromUserId;
		__int64 toUserId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

