///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef NotifyMediaServerRemoveVideo_H
#define NotifyMediaServerRemoveVideo_H

#include "BaseMessage.h"

namespace LyvcMessage {

class NotifyMediaServerRemoveVideo : public BaseMessage{

	public:
		static const id = 45;
		__int64 fromUserId;
		__int64 toUserId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

