///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef NotifyMediaServerUserExit_H
#define NotifyMediaServerUserExit_H

#include "BaseMessage.h"

namespace LyvcMessage {

class NotifyMediaServerUserExit : public BaseMessage{

	public:
		static const id = 41;
		__int64 userId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

