///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef QuitConference_H
#define QuitConference_H

#include "BaseMessage.h"

namespace LyvcMessage {

class QuitConference : public BaseMessage{

	public:
		static const id = 62;
		__int64 conId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

