///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "RegisterUserResponse.h"

string LyvcMessage::RegisterUserResponse::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<bSuccessful>";
	_snprintf(buffer, BUFFERSIZE, "%d", this->bSuccessful);
	xml = xml + buffer;
	xml = xml + "</bSuccessful>";
	xml = xml + "<message>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->message);
	xml = xml + "</message>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::RegisterUserResponse::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "bSuccessful");
	if(tagContent == ""){
		return false;
	}
	this->bSuccessful = atoi(tagContent.c_str());
	this->message = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "message"));
	return true;
}


