///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef RegisterUserResponse_H
#define RegisterUserResponse_H

#include "BaseMessage.h"

namespace LyvcMessage {

class RegisterUserResponse : public BaseMessage{

	public:
		static const id = 195;
		bool bSuccessful;
		string message;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

