///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef RegisterUser_H
#define RegisterUser_H

#include "BaseMessage.h"

namespace LyvcMessage {

class RegisterUser : public BaseMessage{

	public:
		static const id = 194;
		string userName;
		string password;
		string lastName;
		string firstName;
		string email;
		string domain;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

