///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef RejectReceiveFile_H
#define RejectReceiveFile_H

#include "BaseMessage.h"

namespace LyvcMessage {

class RejectReceiveFile : public BaseMessage{

	public:
		static const id = 163;
		__int64 receiverId;
		string fullFileName;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

