///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef RejectContact_H
#define RejectContact_H

#include "BaseMessage.h"

namespace LyvcMessage {

class RejectContact : public BaseMessage{

	public:
		static const id = 117;
		__int64 receiverId;
		string name;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

