///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef RejectAudio_H
#define RejectAudio_H

#include "BaseMessage.h"

namespace LyvcMessage {

class RejectAudio : public BaseMessage{

	public:
		static const id = 74;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

