///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef RejectInviteDesktop_H
#define RejectInviteDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class RejectInviteDesktop : public BaseMessage{

	public:
		static const id = 106;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

