///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef RemoveGroup_H
#define RemoveGroup_H

#include "BaseMessage.h"

namespace LyvcMessage {

class RemoveGroup : public BaseMessage{

	public:
		static const id = 119;
		__int64 groupId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

