///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef RemoveContact_H
#define RemoveContact_H

#include "BaseMessage.h"

namespace LyvcMessage {

class RemoveContact : public BaseMessage{

	public:
		static const id = 118;
		__int64 contactId;
		__int64 groupId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

