///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef SearchContact_H
#define SearchContact_H

#include "BaseMessage.h"

namespace LyvcMessage {

class SearchContact : public BaseMessage{

	public:
		static const id = 120;
		string email;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

