///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "SendFileData.h"

string LyvcMessage::SendFileData::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<isFirstSend>";
	_snprintf(buffer, BUFFERSIZE, "%d", this->isFirstSend);
	xml = xml + buffer;
	xml = xml + "</isFirstSend>";
	xml = xml + "<isFinished>";
	_snprintf(buffer, BUFFERSIZE, "%d", this->isFinished);
	xml = xml + buffer;
	xml = xml + "</isFinished>";
	xml = xml + "<dataLength>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->dataLength);
	xml = xml + buffer;
	xml = xml + "</dataLength>";
	xml = xml + "<compressedLength>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->compressedLength);
	xml = xml + buffer;
	xml = xml + "</compressedLength>";
	xml = xml + "<receiverId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->receiverId);
	xml = xml + buffer;
	xml = xml + "</receiverId>";
	xml = xml + "<fullFileName>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->fullFileName);
	xml = xml + "</fullFileName>";
	xml = xml + "<fileData>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->fileData);
	xml = xml + "</fileData>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::SendFileData::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "isFirstSend");
	if(tagContent == ""){
		return false;
	}
	this->isFirstSend = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "isFinished");
	if(tagContent == ""){
		return false;
	}
	this->isFinished = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "dataLength");
	if(tagContent == ""){
		return false;
	}
	this->dataLength = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "compressedLength");
	if(tagContent == ""){
		return false;
	}
	this->compressedLength = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "receiverId");
	if(tagContent == ""){
		return false;
	}
	this->receiverId = _atoi64(tagContent.c_str());
	this->fullFileName = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "fullFileName"));
	this->fileData = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "fileData"));
	return true;
}


