///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef ServerInternalError_H
#define ServerInternalError_H

#include "BaseMessage.h"

namespace LyvcMessage {

class ServerInternalError : public BaseMessage{

	public:
		static const id = 82;
		string description;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

