///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef SetContactAdmin_H
#define SetContactAdmin_H

#include "BaseMessage.h"

namespace LyvcMessage {

class SetContactAdmin : public BaseMessage{

	public:
		static const id = 185;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

