///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef SetUserPicture_H
#define SetUserPicture_H

#include "BaseMessage.h"

namespace LyvcMessage {

class SetUserPicture : public BaseMessage{

	public:
		static const id = 184;
		__int32 fileLength;
		__int64 receiverId;
		string extendFileName;
		string fileData;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

