///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "SetUserPicture.h"

string LyvcMessage::SetUserPicture::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<fileLength>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->fileLength);
	xml = xml + buffer;
	xml = xml + "</fileLength>";
	xml = xml + "<receiverId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->receiverId);
	xml = xml + buffer;
	xml = xml + "</receiverId>";
	xml = xml + "<extendFileName>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->extendFileName);
	xml = xml + "</extendFileName>";
	xml = xml + "<fileData>";
	xml = xml + BaseMessage::encodeHtmlEscape(this->fileData);
	xml = xml + "</fileData>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::SetUserPicture::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "fileLength");
	if(tagContent == ""){
		return false;
	}
	this->fileLength = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "receiverId");
	if(tagContent == ""){
		return false;
	}
	this->receiverId = _atoi64(tagContent.c_str());
	this->extendFileName = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "extendFileName"));
	this->fileData = BaseMessage::decodeHtmlEscape(BaseMessage::getStringBetweenTag(xmlString, "fileData"));
	return true;
}


