///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef StartConference_H
#define StartConference_H

#include "BaseMessage.h"

namespace LyvcMessage {

class StartConference : public BaseMessage{

	public:
		static const id = 37;
		__int64 conferenceId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

