///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef StopReceiveFile_H
#define StopReceiveFile_H

#include "BaseMessage.h"

namespace LyvcMessage {

class StopReceiveFile : public BaseMessage{

	public:
		static const id = 167;
		__int64 receiverId;
		string fullFileName;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

