///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef StopReceiveAudio_H
#define StopReceiveAudio_H

#include "BaseMessage.h"

namespace LyvcMessage {

class StopReceiveAudio : public BaseMessage{

	public:
		static const id = 76;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

