///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef StopReceiveVideo_H
#define StopReceiveVideo_H

#include "BaseMessage.h"

namespace LyvcMessage {

class StopReceiveVideo : public BaseMessage{

	public:
		static const id = 81;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

