///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef StopReceiveDesktop_H
#define StopReceiveDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class StopReceiveDesktop : public BaseMessage{

	public:
		static const id = 108;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

