///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef StopSendControlDesktop_H
#define StopSendControlDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class StopSendControlDesktop : public BaseMessage{

	public:
		static const id = 109;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

