///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef StopSendAudio_H
#define StopSendAudio_H

#include "BaseMessage.h"

namespace LyvcMessage {

class StopSendAudio : public BaseMessage{

	public:
		static const id = 75;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

