///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef StopReceiveControlDesktop_H
#define StopReceiveControlDesktop_H

#include "BaseMessage.h"

namespace LyvcMessage {

class StopReceiveControlDesktop : public BaseMessage{

	public:
		static const id = 107;
		__int64 conferenceId;
		__int64 senderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

