///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef StopSpeak_H
#define StopSpeak_H

#include "BaseMessage.h"

namespace LyvcMessage {

class StopSpeak : public BaseMessage{

	public:
		static const id = 173;
		__int64 speakerId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

