///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef SystemMessage_H
#define SystemMessage_H

#include "BaseMessage.h"

namespace LyvcMessage {

class SystemMessage : public BaseMessage{

	public:
		static const id = 192;
		__time64_t sendDate;
		__int64 receiverId;
		string title;
		string content;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

