///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef UpdateContactStatus_H
#define UpdateContactStatus_H

#include "BaseMessage.h"

namespace LyvcMessage {

class UpdateContactStatus : public BaseMessage{

	public:
		static const id = 112;
		bool bIsCommon;
		__int32 status;
		__int64 contactId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

