///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef UserLoginResponse_H
#define UserLoginResponse_H

#include "BaseMessage.h"

namespace LyvcMessage {

class UserLoginResponse : public BaseMessage{

	public:
		static const id = 50;
		__int64 userId;
		string message;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

