///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef UserChannelBroken_H
#define UserChannelBroken_H

#include "BaseMessage.h"

namespace LyvcMessage {

class UserChannelBroken : public BaseMessage{

	public:
		static const id = 111;
		__int64 userId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

