///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef UserJoinConference_H
#define UserJoinConference_H

#include "BaseMessage.h"

namespace LyvcMessage {

class UserJoinConference : public BaseMessage{

	public:
		static const id = 69;
		__int32 avCompressionCardChannelNumber;
		__int64 conId;
		__int64 roleId;
		__int64 userId;
		string userName;
		string firstName;
		string lastName;
		string email;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

