///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef UserDetail_H
#define UserDetail_H

#include "BaseMessage.h"

namespace LyvcMessage {

class UserDetail : public BaseMessage{

	public:
		static const id = 126;
		__int32 userRole;
		__int64 userId;
		string userName;
		string firstName;
		string lastName;
		string email;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

