///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef WatchUser_H
#define WatchUser_H

#include "BaseMessage.h"

namespace LyvcMessage {

class WatchUser : public BaseMessage{

	public:
		static const id = 169;
		__int32 viewMode;
		__int64 receiverId;
		string beWatchedIds;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

