///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef WritingMessage_H
#define WritingMessage_H

#include "BaseMessage.h"

namespace LyvcMessage {

class WritingMessage : public BaseMessage{

	public:
		static const id = 181;
		bool bIsWriting;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

