///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#include "stdafx.h"
#include "YuntaiHolderBroadcast.h"

string LyvcMessage::YuntaiHolderBroadcast::toXML()
{
	const int BUFFERSIZE=64;
	char buffer[BUFFERSIZE];
	string xml;
	xml = xml + "<lyvcmessage>";
	xml = xml + "<id>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", id);
	xml = xml + buffer;
	xml = xml + "</id>";
	xml = xml + "<_senderid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_senderId);
	xml = xml + buffer;
	xml = xml + "</_senderid>";
	xml = xml + "<_conferenceid>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->_conferenceId);
	xml = xml + buffer;
	xml = xml + "</_conferenceid>";
	xml = xml + "<commPort>";
	_snprintf(buffer, BUFFERSIZE, "%I32d", this->commPort);
	xml = xml + buffer;
	xml = xml + "</commPort>";
	xml = xml + "<holderId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->holderId);
	xml = xml + buffer;
	xml = xml + "</holderId>";
	xml = xml + "<receiverId>";
	_snprintf(buffer, BUFFERSIZE, "%I64d", this->receiverId);
	xml = xml + buffer;
	xml = xml + "</receiverId>";
	xml = xml + "</lyvcmessage>";
	return xml;
}

bool LyvcMessage::YuntaiHolderBroadcast::fromXML(string& xmlString)
{
	string tagContent;
	
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_senderid");
	if(tagContent == ""){
		return false;
	}
	this->_senderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "_conferenceid");
	if(tagContent == ""){
		return false;
	}
	this->_conferenceId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "commPort");
	if(tagContent == ""){
		return false;
	}
	this->commPort = atoi(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "holderId");
	if(tagContent == ""){
		return false;
	}
	this->holderId = _atoi64(tagContent.c_str());
	tagContent = BaseMessage::getStringBetweenTag(xmlString, "receiverId");
	if(tagContent == ""){
		return false;
	}
	this->receiverId = _atoi64(tagContent.c_str());
	return true;
}


