///////////////////////////////
// Message definition file
// Generated by lyvc Message
///////////////////////////////

#ifndef YuntaiHolderBroadcast_H
#define YuntaiHolderBroadcast_H

#include "BaseMessage.h"

namespace LyvcMessage {

class YuntaiHolderBroadcast : public BaseMessage{

	public:
		static const id = 180;
		__int32 commPort;
		__int64 holderId;
		__int64 receiverId;

	public:
		virtual string toXML();
		virtual bool fromXML(string& xmlString);

}; // class

}; // namespace

#endif

