//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FLVCC.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ROOM_VIEW                   101
#define IDR_HTML_SHOWXMLDLG             104
#define IDD_FILETRANSFERMGRDLG          105
#define IDR_HTML_ADVERTIZEDLG           106
#define IDD_CONTACT_DLG                 109
#define IDD_CONFERENCE_DLG              110
#define IDD_SYSINFO_DLG                 113
#define IDR_MAINFRAME                   125
#define IDS_QUIT                        127
#define IDR_MENU_TRAY                   142
#define IDD_CHAT_DLG                    144
#define IDC_LINK                        149
#define IDR_MAINFRAME_MEET              162
#define IDD_ATTENDER_DLG                165
#define IDD_LOGIN_DIALOG                182
#define IDR_GIF1                        183
#define IDD_CONF_INFO_DLG               185
#define IDD_OPTION_GENERAL_DLG          186
#define IDI_LOGOUT                      187
#define IDD_DIR_DLG                     188
#define IDD_CONTACT_LIST_DLG            190
#define IDD_CONTACT_INFO_DLG            191
#define IDB_CONTACT                     202
#define IDB_CONFERENCE                  203
#define IDB_SYSMSG                      204
#define IDB_TOP                         205
#define IDB_CONF_TREE                   209
#define IDB_SYSMSG_TREE                 210
#define IDB_CONTACT_TREE                211
#define IDB_MSG                         229
#define IDR_ATTENDERDLG_POPUP           230
#define IDD_ADDCONTACTGROUP             231
#define IDR_MARK                        232
#define IDD_FILE_TRANSFER_DLG           233
#define IDB_ABOUT                       235
#define IDR_CONTACTDLG                  237
#define IDD_LEAVEWORD_DLG               238
#define IDR_LOGOUT                      238
#define IDD_ADD_CONTACT_STEP1_DLG       239
#define IDR_TRAINING                    239
#define IDD_ADD_CONTACT_STEP2_DLG       240
#define IDR_TRAININGROOM                240
#define IDR_CONSULTING                  241
#define IDD_STATUS_DLG                  242
#define IDR_CONSULTINGROOM              242
#define IDD_SHOWXML_DLG                 243
#define IDD_ADD_CONTACT_STEP3_DLG       245
#define IDB_CONTACTLIST                 248
#define IDB_CONTACTLISTBK               249
#define IDB_ADDCONTACT                  250
#define IDB_CORNER                      255
#define IDB_LOGINBK                     256
#define IDB_LOGINLOGO                   257
#define IDB_LOGIN1                      258
#define IDB_LOGIN2                      259
#define IDI_MEETING                     264
#define IDD_ATTENDERLIST_DLG            265
#define IDB_FONT                        266
#define IDB_SENDMSG                     267
#define IDB_SHOWATTENDERLIST            268
#define IDB_HIDEATTENDERLIST            269
#define IDB_SCROLLDOWN                  270
#define IDB_SCROLLUP                    271
#define IDB_ATTENDERDLG                 272
#define IDB_APPLYDESKTOP                273
#define IDB_SENDFILE                    274
#define IDB_SENDVIDEO                   276
#define IDB_INVITE                      277
#define IDB_HEADPHONE                   278
#define IDB_MIC                         279
#define IDD_PROPPAGE_INTRO              280
#define IDD_PROPPAGE_AUDIO_PLAY         281
#define IDC_COMBO_AUDIO_PLAY_DEVICE     282
#define IDC_BUTTON_PLAY_SAMPLE          283
#define IDC_SLIDER_AUDIO_PLAY_VOLUME    284
#define IDD_PROPPAGE_AUDIO_RECORD       285
#define IDC_COMBO_AUDIO_RECORD_DEVICE   286
#define IDC_SLIDER_AUDIO_RECORD_VOLUME  287
#define IDD_PROPPAGE_VIDEO              288
#define IDB_INTRODUCTION                289
#define IDD_SORTATTENDERS_DLG           290
#define IDB_HEADPHONEMUTE               292
#define IDB_MICMUTE                     293
#define IDB_LISTEN                      294
#define IDB_NOTLISTEN                   295
#define IDB_SENDVIDEO2                  296
#define IDB_INVITE2                     297
#define IDB_SENDFILE2                   298
#define IDB_APPLYDESKTOP2               299
#define IDB_SENDVIDEO3                  300
#define IDB_INVITE3                     301
#define IDB_SENDFILE3                   302
#define IDB_APPLYDESKTOP3               303
#define IDB_NOTSENDVIDEO3               316
#define IDB_NOTSENDVIDEO2               320
#define IDB_NOTSENDVIDEO                321
#define IDB_BITMAP1                     323
#define IDB_RECVFILETAB                 323
#define IDB_SENDFILETAB                 324
#define IDB_BITMAP2                     325
#define IDB_SENDFILETABTOP              325
#define IDD_VIDEO_BG_DLG                327
#define IDB_VIDEOBG                     328
#define IDD_CONTROL_DLG                 330
#define IDD_CONTROLSPEAK_DLG            333
#define IDB_CONTROLSPEAK                334
#define IDD_YUNTAI_DLG                  335
#define IDD_OPTION_VIDEOCONFIG_DLG      337
#define IDD_VIDEOQUALITY_DLG            338
#define IDD_SETMYPICTURE_DLG            342
#define IDB_LOGIN3                      343
#define IDB_ADDCONTACT2                 344
#define IDB_ADDCONTACT3                 345
#define IDB_STATUSBK                    346
#define IDB_SCROLLBAR                   348
#define IDB_SHOWATTENDERLIST2           349
#define IDB_HIDEATTENDERLIST2           351
#define IDB_FONT2                       352
#define IDB_FONT3                       353
#define IDB_ROOMTOPBG                   356
#define IDB_INVITE4                     357
#define IDB_SENDFILE4                   358
#define IDB_APPLYDESKTOP4               359
#define IDB_SENDVIDEO4                  360
#define IDB_SCROLLUP2                   361
#define IDB_SCROLLDOWN2                 362
#define IDB_TASKBARNOTIFIER             363
#define IDB_BUTTON                      364
#define IDB_BUTTONDISABLE               365
#define IDB_CHATDLGBG                   366
#define IDD_OPTION_DLG                  367
#define IDB_GENERALOPTION               368
#define IDB_VIDEOOPTION                 369
#define IDR_SERVER                      370
#define IDD_SERVER_DLG                  371
#define IDD_GETNAMEPASSWORD_DLG         372
#define IDR_CONFERENCEDLG               373
#define IDR_SYSMSG                      374
#define IDD_ADVERTIZEBG_DLG             375
#define IDB_ADBG                        376
#define IDD_ADVERTIZE_DLG               377
#define IDR_ATTENDERDLG_SELF            378
#define IDD_STATUSBAR_DLG               382
#define IDD_USERINFO_DLG                383
#define IDD_USERREGISTER_DLG            384
#define IDD_WHITEBOARD                  385
#define IDD_WHITEBOARDDLG               386
#define IDR_WB_TOOLBAR                  387
#define IDR_COLORTOOLBAR                388
#define IDB_WHITEBOARD                  389
#define IDB_WHITEBOARD2                 390
#define IDB_WHITEBOARD3                 391
#define IDC_RUBBER                      392
#define IDR_MSN_MENU                    393
#define IDD_MSNACCOUNT_DLG              394
#define IDD_MSN_DELCONTACT_DLG          395
#define IDC_NAME                        1001
#define IDC_CONTACT_TREE                1002
#define IDC_GROUPNAME                   1003
#define IDC_BTN_OK                      1004
#define IDC_ADDCONTACT_BTN              1005
#define IDC_REGISTER_NEW                1006
#define IDC_SHOWATTENDERLIST_BTN        1007
#define IDC_UP_BTN                      1008
#define IDC_SCROLLDOWN_BTN              1009
#define IDC_SELECT_RECEIVE_PATH         1010
#define IDC_PASSWD                      1011
#define IDC_SENDMSG                     1014
//#define IDC_REGISTER_BTN                1032
#define IDC_FONT                        1040
#define IDC_CANCEL_LOGIN_BTN            1044
#define IDC_SEND                        1046
#define IDC_SYSINFO_TREE                1060
#define IDC_CONFERENCE_TREE             1063
#define IDC_DIR_TREE                    1067
#define IDC_CHATMSG                     1070
#define IDC_SENDFILE                    1075
#define IDC_LOGIN_BTN                   1119
#define IDC_LOGIN_AS                    1121
#define IDC_EMAIL                       1122
#define IDC_LOGIN_ANOTHER_BTN           1123
#define IDC_MEMPWD                      1127
#define IDC_GIFPLAY                     1128
#define IDC_CONF_NAME                   1130
#define IDC_CONF_DESC                   1131
#define IDC_CONF_START                  1132
#define IDC_CONF_END                    1133
#define IDC_CONF_STATUS                 1135
#define IDC_AUTOLOGIN                   1138
#define IDC_STATUS                      1139
#define IDC_AUTORUN                     1140
#define IDC_ALERTQUITCONF               1144
#define IDC_RECEIVE_PATH                1145
#define IDC_CONTACT_LIST                1146
#define IDC_CONTACT_PROPERTY_NAME       1147
#define IDC_CONTACT_PROPERTY_EMAIL      1148
#define IDC_CONTACT_PROPERTY_STATUS     1150
#define IDC_CONTACT_PROPERTY_GROUP      1152
#define IDC_COMBO_VIDEO_DEVICE          1156
#define IDC_MIC_MUTE                    1163
#define IDC_WAVEOUT_MUTE                1164
#define IDC_VOLUME_MIC                  1165
#define IDC_VOLUME_WAVEOUT              1166
#define IDC_FILETRANSFER_PROGRESS       1168
#define IDC_BTN_ACCEPTFILE              1170
#define IDC_BTN_REJECTFILE              1171
#define IDC_BTN_FILEBROKEN              1172
#define IDC_LEAVEWORD                   1181
#define IDC_SEARCH_RESULT               1182
#define IDC_STATIC1                     1183
#define IDC_STATIC2                     1184
#define IDC_STATIC3                     1185
#define IDC_CONNECT_PORT                1188
#define IDC_CONNECT_IP                  1189
#define IDC_USERNAME                    1192
#define IDC_LOGIN_OK                    1198
#define IDC_LOGIN_CANCEL                1199
#define IDC_CHAT_TAB                    1200
#define IDC_VIDEO_WINDOW                1201
#define IDC_SCROLLUP_BTN                1202
#define IDC_SENDTO                      1205
#define IDC_STATIC_REVISION             1207
#define IDC_ATTENDERS                   1208
#define IDC_INVITE                      1209
#define IDC_DOWN_BTN                    1210
#define IDC_SORT_BTN                    1211
#define IDC_SENDVIDEO                   1212
#define IDC_APPLYDESKTOP                1213
#define IDC_LISTEN_BTN                  1214
#define IDC_SORTBYNAME_BTN              1215
#define IDC_QUITFULLSCREENDESKTOP       1216
#define IDC_SENDLIST                    1217
#define IDC_SELECTALL                   1219
#define IDC_CANCEL_SELECTEDTASK_BTN     1220
#define IDC_OPEN_RECEIVED               1221
#define IDC_ADDTASK_BTN                 1222
#define IDC_CURRENTTRANSFER             1223
#define IDC_PROPERTY                    1224
#define IDC_VIDEO                       1225
#define IDC_LISTEN_LIST                 1227
#define IDC_USER_LIST                   1228
#define IDC_LOOKVIDEO_LIST              1229
#define IDC_CONTROLSPEAK_LIST           1230
#define IDC_VIEW_NORMAL                 1232
#define IDC_VIEW_VGA                    1233
#define IDC_VIEW_CIF                    1234
#define IDC_VIEW_QCIF                   1235
#define IDC_SELECT_ALL_CHK              1236
#define IDC_SELECT_ALL_CHK2             1237
#define IDC_SHOWTEXT                    1238
#define IDC_STATIC_VIDEO                1238
#define IDC_SHOWTEXT2                   1239
#define IDC_STATIC_AUDIO                1239
#define IDC_VIEW_TWO                    1240
#define IDC_NUMBEROFVIDEO               1241
#define IDC_SELECT_ALL_CHK3             1242
#define IDC_SERVERTYPE                  1243
#define IDC_SERVERLIST                  1243
#define IDC_APPOINTSPEAKER_BTN          1244
#define IDC_STOPSPEAKER_BTN             1246
#define IDC_BTN_LEFT                    1248
#define IDC_BTN_RIGHT                   1249
#define IDC_BTN_DOWN                    1250
#define IDC_BTN_UP                      1251
#define IDC_BTN_ZOOMIN                  1252
#define IDC_BTN_ZOOMOUT                 1253
#define IDC_STATIC_USERLIST             1254
#define IDC_STATIC_VIEWMODE             1255
#define IDC_BTN_ANSWER                  1256
#define IDC_BTN_STOPANSWER              1257
#define IDC_STATIC_FRAME                1258
#define IDC_BTN_APPLY                   1259
#define IDC_COMBO_CONTROLLIST           1261
#define IDC_COMBO_SERIALPORT            1262
#define IDC_WRITINGMSG                  1263
#define IDC_FPS                         1264
#define IDC_KEYFRAME                    1265
#define IDC_DEFAULT_BTN                 1266
#define IDC_COMBO_VIDEOSIZE             1267
#define IDC_FRAMERATE                   1268
#define IDC_ERRORNUMBER                 1269
#define IDC_PREVIEW                     1270
#define IDC_SELECTFILE_BTN              1271
#define IDC_CHECK1                      1272
#define IDC_DISPLAYMYPICTURE            1272
#define IDC_REMEMBERUSERNAME            1272
#define IDC_REMEMBERME                  1272
#define IDC_CHECKALL                    1272
#define IDC_CHANGEPASSWORD              1272
#define IDC_LOGIN_AFTER_REGISTER        1272
#define IDC_PICTUREPATH                 1273
#define IDC_LOCAL_VIRTUAL_VIDEO         1274
#define IDC_SELECTSERVER                1275
#define IDC_ENTERUSERNAME               1276
#define IDC_ENTERPASSWORD               1277
#define IDC_PASSWORD                    1278
#define IDC_LOGININGTEXT                1280
#define IDC_REMEMBERPASSWORD            1281
#define IDC_RESET                       1283
#define IDC_APPLY_BTN                   1284
#define IDC_CLOSE_BTN                   1287
#define IDC_SERVERNAME                  1288
#define IDC_SERVERIP                    1289
#define IDC_SERVERPORT                  1290
#define IDC_STAYTIME                    1292
#define IDC_CONFUSERNUM                 1293
#define IDC_APPLY                       1294
#define IDC_FIRSTNAME                   1295
#define IDC_LASTNAME                    1296
#define IDC_NEWPASSWORD                 1299
#define IDC_CONFIRMNEWPASSWORD          1300
#define IDC_STATIC_PWD                  1303
#define IDC_STATIC_NEWPWD               1304
#define IDC_STATIC_CONFIRMPWD           1305
#define IDC_CONFIRMPASSWORD             1306
#define IDC_CONF_DOCS                   1307
#define IDC_PREVBOARD_BTN               1309
#define IDC_NEXTBOARD_BTN               1310
#define IDC_CURRENTBOARD                1311
#define IDC_WHITEBOARD_BTN              1312
#define IDC_MSNACCOUNT                  1313
#define IDC_MSNPASSWORD                 1314
#define IDC_MSN_HIDECONTACT             1315
#define IDC_MSN_DELCONTACT              1316
#define ID_VIEW_CONFUSERLIST            32801
#define ID_ADD_CONTACT                  32808
#define ID_DEL_CONTACT                  32810
#define ID_PROPERTY_CONTACT             32814
#define ID_CREATE_CONTACT_GROUP         32816
#define ID_DEL_CONTACT_GROUP            32817
#define ID_RENAME_CONTACT_GROUP         32818
#define ID_CREATE_CONFERENCE            32864
#define ID_JOIN_CONFERENCE              32865
#define ID_LOOK_CONFERENCE              32866
#define ID_ALWAYS_TOP                   32868
#define ID_SHOW_ONLY_ONLINE             32869
#define ID_OPTION                       32873
#define ID_APPLY_VIDEO                  32916
#define ID_STOP_RECEIVE_VIDEO           32917
#define ID_APPLY_AUDIO                  32918
#define ID_STOP_RECEIVE_AUDIO           32919
#define ID_QUIT_CONFERENCE              32956
#define ID_HELP_CONTENT                 32981
#define ID_SEARCH_CONTACT               32996
#define ID_LOGIN                        33026
#define ID_LOGOUT                       33027
#define ID_CLOSE                        33039
#define ID_CREATE_INSTANTCONF           33041
#define ID_ABOUT                        33043
#define ID_EXIT                         33044
#define ID_MENU_HIDE                    33045
#define ID_MENU_SHOW                    33046
#define ID_START_DESKTOP                33065
#define ID_STOP_DESKTOP                 33066
#define ID_START_DESKTOP_SERVER         33069
#define ID_STOP_DESKTOP_SERVER          33070
#define ID_APPLY_DESKTOP_SHARE          33071
#define ID_STOP_DESKTOP_SHARE           33072
#define ID_APPLY_DESKTOP_CONTROL        33073
#define ID_STOP_DESKTOP_CONTROL         33075
#define ID_LOOKVIDEO                    33086
#define ID_STOPLOOKVIDEO                33087
#define ID_CHAT                         33088
#define ID_APPLY_DESKTOP                33091
#define ID_INVITE_DESKTOP               33092
#define ID_APPLY_CONTROL                33093
#define ID_STOP_CONTROL                 33094
#define ID_STOP_DESKTOP_RECEIVE         33095
#define ID_STOP_DESKTOP_SEND            33096
#define ID_STOP_RECEIVE_CONTROL         33098
#define ID_STOP_RECEIVE_DESKTOP_CONTROL 33100
#define ID_SENDFILE                     33101
#define ID_OPEN_RECEIVEDFILE            33102
#define ID_CONFERENCE_INFO              33103
#define ID_STOP_LISTEN                  33105
#define ID_START_LISTEN                 33106
#define ID_RECEIVE_AUDIO                33119
#define ID_STOP_AUDIO                   33120
#define ID_INVITE_CONFERENCE            33122
#define ID_SEND_FILE                    33123
#define ID_OPEN_RECEIVED                33124
#define ID_MARK                         33126
#define ID_PEN_COLOR                    33128
#define ID_PEN_BLUE                     33132
#define ID_PEN_RED                      33133
#define ID_PEN_GREEN                    33134
#define ID_PEN_S                        33144
#define ID_PEN_L                        33145
#define ID_PEN_M                        33146
#define ID_MARK_EXIT                    33147
#define ID_SENDFILETOALL                33155
#define ID_SEND_LEAVEWORD               33158
#define ID_ADDCONTACT                   33170
#define ID_ADDGROUP                     33171
#define ID_BEGINCONF                    33173
#define ID_CHECKCONTACTINFO             33174
#define ID_DELETECONTACT                33175
#define ID_SEND_EMAIL                   33177
#define ID_RENAMEGROUP                  33178
#define ID_DELGROUP                     33179
#define ID_LOOK_LEAVEWORDS              33186
#define ID_LOOK_SYSMSG                  33187
#define ID_GOTO_CONF_WEBSERVER          33188
#define ID_HISTORY_CONF                 33190
#define ID_AV_WIZARD                    33193
#define ID_KICK_USER                    33208
#define ID_MOVE_CONTACT_TO_GROUP        33212
#define ID_SORTATTENDERS                33213
#define ID_LOCALVIDEO                   33215
#define ID_SHOW_FILETRANSFERMGR         33216
#define ID_VIDEO_ON_TOP                 33217
#define ID_VIEW_NORMAL                  33220
#define ID_VIEW_FOUR_CIF                33222
#define ID_VIEW_ONE_VGA                 33223
#define ID_VIEW_SIXTEEN_QCIF            33224
#define ID_VIEW_POPUP                   33226
#define ID_SWITCH_VIEWMODE              33227
#define ID_TOPMOST                      33232
#define ID_QCIF                         33235
#define ID_CIF                          33236
#define ID_VGA                          33238
#define ID_FULLSCREEN                   33239
#define ID_CENTER_CONTROL               33241
#define ID_VIEW_TWO                     33243
#define ID_VIEW_DIALOG                  33244
#define ID_APPLYSPEAK                   33246
#define ID_CONTROLSPEAK                 33247
#define ID_SEPRATE_VIDEO                33250
#define ID_YUNTAICONTROL                33252
#define ID_APPLY_CONTACT                33253
#define ID_VIDEOQUALITY_GOOD            33258
#define ID_VIDEOQUALITY_NORMAL          33259
#define ID_VIDEOQUALITY_BAD             33260
#define ID_CHANGEVIDEOQUALITY           33262
#define ID_VIEW_CONFHISTORY             33264
#define ID_VIEW_CHATLOG                 33265
#define ID_SETMYPICTURE                 33268
#define ID_SETPICTURE                   33269
#define ID_COPYCONTACTTOUSER            33272
#define ID_COPYCONTACTTOALL             33273
#define ID_COPYCONTACTTOGROUP           33275
#define ID_ADDFROMCOMMON                33277
#define ID_ADDSERVER                    33284
#define ID_CHECKSERVER                  33285
#define ID_REMOVESERVER                 33286
#define ID_LOGINSERVER                  33287
#define ID_LOGOUTSERVER                 33288
#define ID_CANCELLOGINSERVER            33289
#define ID_REGISTERNEW                  33291
#define ID_LOGINANOTHER                 33293
#define ID_VIEWCONFHISTORY              33298
#define ID_LOOKMESSAGE                  33302
#define ID_DELMESSAGE                   33303
#define ID_DELALLMESSAGE                33304
#define ID_KICKUSER                     33306
#define ID_DELETECONFUSER               33308
#define ID_COMMONCONTACTMGR             33310
#define ID_CREATEFORMALCONF             33311
#define ID_CONFMODEMGR                  33313
#define ID_SYSTEMROLEMGR                33314
#define ID_SELFINFOMGR                  33315
#define ID_EDITCONFERENCE               33316
#define ID_DELETECONFERENCE             33317
#define ID_EDITCONFERENCENOTICE         33319
#define ID_SENDSYSTEMMSG                33321
#define ID_LOOKCONFERENCENOTICE         33324
#define ID_NEW_WHITEBOARD               33325
#define ID_SAVE_WHITEBOARD              33326
#define IDT_DELETE                      33327
#define IDT_SELECT                      33328
#define IDT_LINE                        33329
#define IDT_RECTANGLE                   33330
#define IDT_ELLIPSE                     33331
#define IDT_CIRCLE                      33332
#define IDT_POLY                        33333
#define IDT_CURVE                       33334
#define IDT_TEXT                        33335
#define ID_WIDTH_THIN                   33336
#define ID_WIDTH_NORMAL                 33337
#define ID_WIDTH_WIDE                   33338
#define ID_FILL_FALSE                   33339
#define ID_FILL_TRUE                    33340
#define ID_COLOR_BLACK                  33343
#define ID_COLOR_WHITE                  33344
#define ID_COLOR_GRAY                   33345
#define ID_COLOR_RED                    33346
#define ID_COLOR_GREEN                  33347
#define ID_COLOR_BLUE                   33348
#define ID_COLOR_PINK                   33349
#define ID_COLOR_YELLOW                 33350
#define ID_COLOR_CYAN                   33351
#define ID_SMALL_TEXT                   33352
#define ID_NORMAL_TEXT                  33353
#define ID_BIG_TEXT                     33354
#define ID_RUBBER                       33355
#define ID_MSN_LOGIN                    33356
#define ID_MSN_LOGOUT                   33358
#define ID_MSN_ACCOUNT                  33359
#define ID_MSN_SENDMSG                  33360
#define ID_MSN_FINDADD                  33363
#define ID_MSN_DELCONTACT               33365
#define ID_MSN_ADDGROUP                 33369
#define ID_MSN_DELGROUP                 33370
#define ID_MSN_RENAMEGROUP              33371
#define ID_MSN_MOVECONTACT              33374
#define ID_MSN_VIEWHISTORY              33376
#define ID_MSN_CONTACTINFO              33378
#define ID_MSN_ONLINE                   33379
#define ID_MSN_BUSY                     33380
#define ID_MSN_BERIGHTBACK              33381
#define ID_MSN_AWAY                     33382
#define ID_MSN_ONTHEPHONE               33383
#define ID_MSN_OUTTOLUNCH               33384
#define ID_MSN_APPEAROFFLINE            33385
#define ID_ADDSERVER2                   33387

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        396
#define _APS_NEXT_COMMAND_VALUE         33388
#define _APS_NEXT_CONTROL_VALUE         1317
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
